/**
 * Created by lishiming on 14-6-11.
 */
exports.productarr=
    [
        {
            pid:221
            ,cid:1
            ,title:'制服诱惑 性感旗袍 透视超短裙 复古旗袍'
            ,volume:51
            ,recentvolume:24
            ,org_price:100.00
            ,price:25.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYdXv7ch/6A8uZ.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYdXv9m7/HcLKO.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXiHKP/1554b9.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYdXvecs/kBU5X.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXvyx6/K0hwB.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXuZAX/h8pqV.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXvQ7T/JyYu3.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXvSAo/QwmIG.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXvRLZ/fKkTV.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXw4PQ/u2MFW.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXyxU3/OPYI7.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXubj9/JcGjg.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:222
            ,cid:1
            ,title:'蕾丝日本和服睡裙日系印花性感和服套装 头牌推荐'
            ,volume:65
            ,recentvolume:23
            ,org_price:150
            ,price:45.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYdYfg4v/IQyYs.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYdYfYDu/SJs0M.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYgcll/zGRUZ.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYdY3GH6/AYPUx.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYh30K/yXBON.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYhovJ/bcyPW.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYgYtU/HpkSH.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYh3jx/iQYtA.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:223
            ,cid:1
            ,title:'刺绣旗袍中国风技师夜店服DS演出服'
            ,volume:65
            ,recentvolume:32
            ,org_price:198.00
            ,price:80.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYdYrlm8/6299.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYdYEMrS/dyorf.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYEqa2/hT3wi.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYdYEAKO/IZWhp.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYFfmi/A0tkW.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYFCcc/11p7sm.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYI1QP/gKRoz.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYFbPM/77zmQ.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:224
            ,cid:1
            ,title:'媚火正品 媚火夜店服 性感情趣内衣双层吊带蕾丝半透明睡衣 头牌推荐'
            ,volume:64
            ,recentvolume:31
            ,org_price:218.00
            ,price:80.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/EbeQSIw9/xoCIP.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/EbePSE59/9fHyo.jpg'
                ,'http://pic.yupoo.com/yige2002/EbeQSVVc/5EMbk.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/EbePPWRk/KUsNw.jpg'
                ,'http://pic.yupoo.com/yige2002/EbeQQ1nh/uMotE.jpg'
                ,'http://pic.yupoo.com/yige2002/EbeQR5Dq/bqzLD.jpg'
                ,'http://pic.yupoo.com/yige2002/EbeQRHdv/YipRd.jpg'
                ,'http://pic.yupoo.com/yige2002/EbeQRVSF/An6zB.jpg'
                ,'http://pic.yupoo.com/yige2002/EbeQRKJU/MoEOo.jpg'
                ,'http://pic.yupoo.com/yige2002/EbeQRY7O/fePTc.jpg'
                ,'http://pic.yupoo.com/yige2002/EbeQSrPV/6NTPL.jpg'
                ,'http://pic.yupoo.com/yige2002/EbeQTqJi/8Vmes.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:225
            ,cid:1
            ,title:'[野性潮吹套餐]野性猫女装+奶瓶AV棒+倍力乐三倍持久+印度神油+雅润润滑剂'
            ,volume:64
            ,recentvolume:31
            ,org_price:599.00
            ,price:148.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/EfDRqjSQ/ToAr8.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/EfDRpJau/1TZGs.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDRc5Gj/qzvm6.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDRpDZr/gjXHO.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDRq0pf/NUIIQ.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDRqWUY/M3jgW.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/EfDRphVZ/JQGLB.png'
                ,'http://pic.yupoo.com/yige2002/EfDRptVx/ye0UZ.png'
                ,'http://pic.yupoo.com/yige2002/EfDRoFom/OnP0I.png'
                ,'http://pic.yupoo.com/yige2002/EfDRoSC8/BdSLv.png'
                ,'http://pic.yupoo.com/yige2002/EfDRoW5x/tIXyr.png'
                ,'http://pic.yupoo.com/yige2002/EfDRpbba/eScZU.png'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:226
            ,cid:1
            ,title:'三点式情趣内衣猫女装制服诱惑'
            ,volume:64
            ,recentvolume:31
            ,org_price:89.00
            ,price:25.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/EfDSZ5o0/XG9B8.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/EfDT03SG/14QwTv.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDSZdkd/OKFwX.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDSZLOh/AqnQh.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDSZwrd/YEhu1.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/EfDT0I34/Fuqvd.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDT09x5/62OLh.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDSZWGG/dGILc.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDT0kLB/5MVLJ.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDT13QE/GnyDq.jpg'
                ,'http://pic.yupoo.com/yige2002/EfDT0jo8/na2ra.gif'
                ,'http://pic.yupoo.com/yige2002/EfDSNbNc/11iCld.gif'
                ,'http://pic.yupoo.com/yige2002/EfDT14hR/iMn6O.gif'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:227
            ,cid:1
            ,title:'蕾丝诱惑丁字裤'
            ,volume:64
            ,recentvolume:31
            ,org_price:35.00
            ,price:9.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/EfRz91Cc/zDR6X.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/EfRz9ovI/Cou5V.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRz9AyW/LJgIH.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/EfRyUCdk/ZGDpA.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRza44V/JJhJP.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRzakwJ/606bg.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRzabkZ/yS3uJ.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRzaxVs/8RWVG.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:228
            ,cid:1
            ,title:'性感蕾丝透明丁字裤T字裤 情趣开裆诱惑女士内裤'
            ,volume:64
            ,recentvolume:31
            ,org_price:35.00
            ,price:9.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/EfRzOt1C/zb2Ps.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/EfRzOGeX/DOSfL.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRzOTfI/eOdmX.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/EfRzzPho/Tij9G.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRzA1TP/iKfER.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRzPIJt/jwEaq.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRzPDG1/6Hnym.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        null
    ]