/**
 * Created by lishiming on 14-6-11.
 */
exports.productarr=
    [
        {
            pid:61
            ,cid:4
            ,title:'38频无线跳蛋 居家女人的性福选择'
            ,volume:0
            ,recentvolume:0
            ,org_price:68
            ,price:26.00
            ,state:0
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DNrubbmF/mLt3k.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHfELduD/ZeAO2.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfEL5PP/7Y0sb.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfELObX/Lf6lm.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfE8g4J/ILXWq.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfELKot/2cgxM.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIJfmDCa/QNH0l.jpg'
                ,'http://pic.yupoo.com/yige2002/DIJfmq3l/Cnr6o.jpg'
                ,'http://pic.yupoo.com/yige2002/DIJfmEo7/14PO3M.jpg'
                ,'http://pic.yupoo.com/yige2002/DIJfmMZJ/LWrHa.jpg'
                ,'http://pic.yupoo.com/yige2002/DIJfmTTj/mmWea.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfE8xkn/XVQQ6.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfEMCcF/OgBux.jpg'
                ,null
            ]
        },

        {
            pid:62
            ,cid:4
            ,title:'360度全方位震动按摩乳房按摩神器'
            ,volume:0
            ,recentvolume:0
            ,org_price:60
            ,price:28.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KM9DF/116nzQ.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHfHT2rM/LUw72.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfHgTxW/CdeKG.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHfHSDeh/wTYjf.jpg'
                ,null
            ]
        },

        {
            pid:63
            ,cid:4
            ,title:'360度旋转按摩头充电磨砂AV棒 送女用按摩头套'
            ,volume:0
            ,recentvolume:0
            ,org_price:320
            ,price:79.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KMpYR/i02FQ.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHfVgYQe/V3var.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfVhnrr/Rf140.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfVhi7u/ty3jT.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHfUCfZV/TysyY.jpg'
                ,'http://pic.yupoo.com/yige2002/DOfzZeMn/9ZXbJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DOfzZkUw/DhUSQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DOfzElXO/IVC7T.jpg'
                ,null
            ]
        },

        {
            pid:64
            ,cid:4
            ,title:'便携口袋迷你手机链AV棒 性福无处不在'
            ,volume:0
            ,recentvolume:0
            ,org_price:20
            ,price:12
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DO4C3oiU/dCt6s.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHfZoqUX/AStcz.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfZpolE/HBgIX.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfYLRfC/brItT.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIJjJD8J/70Pgy.jpg'
                ,'http://pic.yupoo.com/yige2002/DIJiZh5U/ts3yk.jpg'
                ,'http://pic.yupoo.com/yige2002/DIJjJoPh/tvneM.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfZplRg/DsQub.jpg'
                ,null
            ]
        },

        {
            pid:65
            ,cid:4
            ,title:'喵星人36变频15震动模式强力马达防水静音有线跳蛋'
            ,volume:0
            ,recentvolume:0
            ,org_price:68
            ,price:42
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KMEOv/sziBp.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHfXkHM7/2yDU3.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfXmgWB/suQo8.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfWIRIu/yFjvt.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfXnsOH/aj5r4.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfXnKEK/OGA7V.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIJiPazn/13kEjO.jpg'
                ,'http://pic.yupoo.com/yige2002/DIJiOXnf/ZfIxi.jpg'
                ,'http://pic.yupoo.com/yige2002/DIJiPtpt/KpckD.jpg'
                ,'http://pic.yupoo.com/yige2002/DIJiPpGl/9VCoL.jpg'
                ,'http://pic.yupoo.com/yige2002/DIJiP1d2/irB5j.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfWKJMA/oyGd3.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfXogqH/CNzBc.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfWLUWA/8Sybe.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfWMpqb/9PgJo.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfXpGSU/zeAsW.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfXqdhJ/dbER2.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfWNjjw/cxPRi.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfXqP2Y/126Lez.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfXrsMa/u6LUI.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfXrVmc/14WCA1.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfXt24A/12px88.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfXsN4y/ZP8YK.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfWHgtR/Yw7oA.jpg'
                ,null
            ]
        },

        {
            pid:66
            ,cid:4
            ,title:'夏奇新品 天使礼物 震动C字裤 7频震动快感无处不在'
            ,volume:0
            ,recentvolume:0
            ,org_price:160
            ,price:81.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KLB1e/1tbcq.gif'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHg0cR7m/OrlTb.jpg'
                ,'http://pic.yupoo.com/yige2002/DHg0e5xq/rB7dU.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfZA8ZX/yuks6.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIK3NmJo/pOfqO.jpg'
                ,'http://pic.yupoo.com/yige2002/DIK4xW7H/j8lLL.jpg'
                ,'http://pic.yupoo.com/yige2002/DIK4xV4N/FIwpC.jpg'
                ,'http://pic.yupoo.com/yige2002/DHg0ekcF/upAWA.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfZAmhp/nuEan.jpg'
                ,'http://pic.yupoo.com/yige2002/DHg0dHmg/28lsH.jpg'
                ,'http://pic.yupoo.com/yige2002/DHg0ekXx/Voz0.jpg'
                ,'http://pic.yupoo.com/yige2002/DHfZANWQ/I0rkd.jpg'
                ,'http://pic.yupoo.com/yige2002/DHg0dYeP/jSL0u.jpg'
                ,null
            ]
        },

        {
            pid:67
            ,cid:4
            ,title:'夏奇正品 战神海浪震动棒 征服你的情欲快感'
            ,volume:0
            ,recentvolume:0
            ,org_price:100
            ,price:59.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KM633/LxJf7.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHg9jg36/NyGGL.jpg'
                ,'http://pic.yupoo.com/yige2002/DHg9jSKn/Hd8dd.jpg'
                ,'http://pic.yupoo.com/yige2002/DHg9jDKW/K6H2E.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIK5Ja8G/NIgAh.jpg'
                ,'http://pic.yupoo.com/yige2002/DIK4Xz8t/QNdMR.jpg'
                ,'http://pic.yupoo.com/yige2002/DIK5Iihk/xC9SS.jpg'
                ,null
            ]
        },

        {
            pid:68
            ,cid:4
            ,title:'奇宝正品 龙猫遥控变频静音防水震动跳蛋'
            ,volume:0
            ,recentvolume:0
            ,org_price:35
            ,price:27.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KNfuh/zUqY8.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHg9Waxx/iSspX.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHg9YZGw/XfH4g.jpg'
                ,'http://pic.yupoo.com/yige2002/DHg9ZNlu/VvbIx.jpg'
                ,'http://pic.yupoo.com/yige2002/DHg9Zpr2/k7FAC.jpg'
                ,'http://pic.yupoo.com/yige2002/DHga0Pk7/R0PoU.jpg'
                ,'http://pic.yupoo.com/yige2002/DHga1sLF/9c5Za.jpg'
                ,'http://pic.yupoo.com/yige2002/DHg9rePk/10plxd.jpg'
                ,'http://pic.yupoo.com/yige2002/DHga6GtF/6XrrC.jpg'
                ,'http://pic.yupoo.com/yige2002/DHga8ZLV/NEVg3.jpg'
                ,'http://pic.yupoo.com/yige2002/DHga9kly/N3JXZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgabGTn/aP7EY.jpg'
                ,null
            ]
        },

        {
            pid:69
            ,cid:4
            ,title:'性福魔盒18频磨砂防水无线遥控跳蛋'
            ,volume:0
            ,recentvolume:0
            ,org_price:68
            ,price:24
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KMk6o/CyzBc.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHgbocug/K8zT0.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgbpxHp/QnwbP.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgbpJiO/60udk.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgboPQ8/LmSVS.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIKl5HUS/iSSu3.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKl6bAI/aHbyl.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKklptD/Ac5kb.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKl69WW/tqMnf.jpg'
                ,null
            ]
        },

        {
            pid:70
            ,cid:4
            ,title:'潮吹之王 仙女棒 醉生梦死的感觉'
            ,volume:0
            ,recentvolume:0
            ,org_price:159
            ,price:63.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DHgc9dBI/12pYzu.jpg'
            ,time:0
            ,gallery:
            [
                null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHgc93vy/baaeu.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKlQTnf/eBVpi.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgc9UaD/HzJqE.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgc9qK5/n7cfc.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgcaeFA/JDeuV.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgcaUE0/CrteE.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgcafef/1vOHK.jpg'
                ,null
            ]
        },

        {
            pid:71
            ,cid:4
            ,title:'激情劈叉裤穿戴空心阳具 亲密伙伴 女性首选'
            ,volume:0
            ,recentvolume:0
            ,org_price:79
            ,price:42
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KM9hS/1SiQH.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHgd3hkd/BfGXB.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgd3Jr9/14791h.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgd2V95/fjdt5.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIKnghL0/RHsnB.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgd2jeb/mKedb.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKng8jB/syDo7.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgd2FMp/K0Vfk.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgd2ZGR/htIu2.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKng7bu/15xfjj.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgd3gBX/dv1JW.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgd3vbr/JvVyr.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgd4sso/cCboT.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgd3urR/zqSYr.jpg'
                ,null
            ]
        },

        {
            pid:72
            ,cid:4
            ,title:'百乐正品电动丰乳器 做坚挺女人，势在必行'
            ,volume:0
            ,recentvolume:0
            ,org_price:180
            ,price:108
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KNHvr/yGnbE.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHgfHoG7/13Levm.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgfHZej/6YBDA.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgf4ypW/GgCN0.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgfIgau/Ub3dh.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIKocnzK/auEgt.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKochaQ/Pt6QL.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKocDfB/Fsd85.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgfHG3W/CLuKG.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgfHZ7N/v8az5.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKocim8/11pFGR.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgfIIQ3/14Yrm6.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgfIoFd/113wny.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgfIIaV/rbWei.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgfJKU5/ga6sj.jpg'
                ,null
            ]
        },

        {
            pid:73
            ,cid:4
            ,title:'百乐派蒂拉 G点阴蒂双震30频振动棒 头牌推荐'
            ,volume:0
            ,recentvolume:0
            ,org_price:160
            ,price:81.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DNjrAdnm/7JAIl.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHghLUub/rEcpA.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghMapy/mE7GT.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghNXsr/IQDEv.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghMT33/qkrVs.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghNwQS/750Tn.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghajoL/DjpsG.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIKq8Biy/5NQCD.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKq8Cdx/sKDvs.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghNdRy/2qyRC.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghM8BM/Y16uV.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghMsgO/N7bwX.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghMGjc/eGaY6.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghNahC/HQGBy.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKq8Nf4/95CFA.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKq8CSu/grlr6.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghNiDU/Y9jKt.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKq93Du/ioQt0.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKq8d5h/VMJ2V.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghNsOg/m2Irs.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghNMSS/12EKaw.jpg'
                ,'http://pic.yupoo.com/yige2002/DHghOVTj/1QXwH.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgh8yjC/beASR.jpg'
                ,null
            ]
        },

        {
            pid:74
            ,cid:4
            ,title:'百乐真品招蜂引蝶伸缩转珠棒 体验被塞满的感觉'
            ,volume:0
            ,recentvolume:0
            ,org_price:199
            ,price:82.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3K9TxX/3vnEj.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHkWoOAI/9aH8l.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkWpdlW/mVIzy.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkWpIcb/LJ9dL.png'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIJbFrrx/1rX56.jpg'
                ,'http://pic.yupoo.com/yige2002/DIJbFKki/8HWLs.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkWpAyT/STLzK.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkWpgUL/BclJb.gif'
                ,'http://pic.yupoo.com/yige2002/DIJbFgqM/xpJ7i.png'
                ,'http://pic.yupoo.com/yige2002/DHkWpwto/AEC45.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkWpD6J/OvYh5.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkWpJQH/7gqvP.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkVM08b/7Zcjx.png'
                ,null
            ]
        },

        {
            pid:75
            ,cid:4
            ,title:'蒂贝正品 惊蛇之草轻触防水20频震动棒'
            ,volume:0
            ,recentvolume:0
            ,org_price:320
            ,price:192
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KMB4z/aX7Yt.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHgt1WL0/63Tir.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgt1t5g/TSUs7.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHgr8oLF/vpiIU.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgrawhS/17bv3.jpg'
                ,'http://pic.yupoo.com/yige2002/DHgrdphv/yV662.jpg'
                ,null
            ]
        },

        {
            pid:76
            ,cid:4
            ,title:'蒂贝正品双马达震动LED夜灯按键隐形穿戴蝴蝶'
            ,volume:0
            ,recentvolume:0
            ,org_price:210
            ,price:102
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KNKvD/hiLqM.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHkXDPAO/bKQCV.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkXEecj/rjO21.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkX0cqB/KTQ4t.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIKqS1BL/aKEYs.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKrCZxS/jjWjA.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKrC8dX/10QBXA.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkXEu5r/5p404.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkXEFKb/11QF5g.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkXEHV4/V3A5U.jpg'
                ,null
            ]
        },

        {
            pid:77
            ,cid:4
            ,title:'邦爱正品7频美国大兵仿真阳具'
            ,volume:0
            ,recentvolume:0
            ,org_price:356
            ,price:103.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KNe4h/vTCEH.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHkYriGY/eetng.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkXNp7P/ijCln.jpg'
                ,'http://pic.yupoo.com/yige2002/DNtbsnKA/F3Kzt.jpg'
                ,'http://pic.yupoo.com/yige2002/DNtbM572/U6KIa.jpg'
                ,'http://pic.yupoo.com/yige2002/DNtbJiCf/YbI7q.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIKsoMkg/10Xtv0.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKsojl8/pdjJO.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkXNIIV/4gdyc.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkYrMfy/aFhsO.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkYrZ60/6Q9fA.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkXOnA5/azLfN.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkYsqsz/P8alM.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkYsTQz/kXLDi.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkYsY8F/11vN2s.jpg'
                ,null
            ]
        },

        {
            pid:78
            ,cid:4
            ,title:'小老二软蛋'
            ,volume:0
            ,recentvolume:0
            ,org_price:55
            ,price:42
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DNlMWJeY/kCaW9.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHkZiXnR/MwBDQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkZiY6c/QFnTp.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkZjlMx/7RJcY.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkZjG52/11tyIq.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIKtvGx9/cIMKn.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKtw88e/OHwgr.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKtvNAp/cc1G6.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkZjiqa/FBxn8.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkZjk2B/waPIK.jpg'
                ,'http://pic.yupoo.com/yige2002/DHkZjsOU/Z75Ed.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKtvxej/JiTtw.jpg'
                ,null
            ]
        },

        {
            pid:79
            ,cid:4
            ,title:'蒂贝玉兔旋风女用自慰G点转珠震动按摩棒'
            ,volume:0
            ,recentvolume:0
            ,org_price:196
            ,price:110.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOgPtZqR/vnE1e.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOgPOJj9/pPCnz.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl0QqwO/mUxCz.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DOgPPTo6/Yufa.jpg'
                ,'http://pic.yupoo.com/yige2002/DOgPPruR/4OLYS.jpg'
                ,'http://pic.yupoo.com/yige2002/DOgPQb9X/Dagte.gif'
                ,'http://pic.yupoo.com/yige2002/DOgPT3Tz/1jAeE.jpg'
                ,null
            ]
        },

        {
            pid:80
            ,cid:4
            ,title:'雷霆真品 转珠棒 雷霆之势 高潮已至'
            ,volume:0
            ,recentvolume:0
            ,org_price:128
            ,price:81.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3KOoM7/jsxEM.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHl1lF8t/2jiPN.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl1m36r/31eRM.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl0I6Hn/shSN5.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl1m8C5/eJKs1.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl1mRR9/9XPhL.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DIKutrov/OTxSe.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKved5w/h5eq1.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKutGYv/6yo4o.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKves8O/5DAZI.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl1mqdk/yCqCH.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl1myDa/1hMQh.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl1mqZZ/9m3PR.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl1mNLq/Mbgkh.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKveFEF/pqlEs.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl1mLMf/fFa0c.jpg'
                ,'http://pic.yupoo.com/yige2002/DIKve1BZ/boyHT.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl1newB/14hhT9.jpg'
                ,'http://pic.yupoo.com/yige2002/DHl0JglY/n1vfR.jpg'
                ,null
            ]
        },

        null
    ]