/**
 * Created by lishiming on 14-6-11.
 */
exports.productarr=
    [
        {
            pid:600
            ,cid:4
            ,title:'阴道哑铃 特惠'
            ,volume:72
            ,recentvolume:29
            ,org_price:299
            ,price:258.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DO6hmjUb/LADt7.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DO6hmbYG/TOPvf.jpg'
                ,'http://pic.yupoo.com/yige2002/DO6hlRs4/RBT2A.jpg'
                ,'http://pic.yupoo.com/yige2002/DO6hmprO/IrcG0.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUtUH4I/mwk1x.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtKtdi/skBGV.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtVfOl/dwiHn.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtKOcx/4bFIa.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtVC6D/fTd2T.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtVLh7/14R4sZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtVYdd/BUxMy.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtWTez/cYbqL.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtWlSL/eFgcB.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtWzNW/fC4qE.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtM40n/15rjDg.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtWSt9/HgiP.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtXfgJ/148cQX.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtX9yx/hh4cz.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtMRNL/11e4Tt.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtXENK/HmKxn.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtXRt1/PcC4y.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtZ72L/aPxig.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtZjhB/7CSEI.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtYDqG/J6l7w.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtYCS4/AVbOh.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:601
            ,cid:4
            ,title:'诺兰音乐人 特惠'
            ,volume:67
            ,recentvolume:18
            ,org_price:998
            ,price:399.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DO6iocFf/f6G0y.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DO6ino2O/121ieL.jpg'
                ,'http://pic.yupoo.com/yige2002/DO6i3Msk/uowfl.jpg'
                ,'http://pic.yupoo.com/yige2002/DO6inW9R/j7o26.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUuI4dE/9dF7u.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuJ4bt/8UyhD.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuJhAn/GVcjT.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuIXSO/zmqeN.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuK6Ge/hnfJL.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuMf1C/vlxoJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuOUx6/DTcsU.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuREpO/27hzu.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuSUJT/pHLH3.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:602
            ,cid:4
            ,title:'香港诺兰ELYI艾怡 金属迷你av震动按摩棒 特惠'
            ,volume:63
            ,recentvolume:24
            ,org_price:678
            ,price:356.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkyV3ch/7ByQB.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkyVsJn/wkEs.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyzVuN/HBwhB.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyVwDV/qTrcb.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DOkyAapq/ZLmDc.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyAhDK/IP3S9.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyVU5U/Id4tk.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyAy6L/kbRW5.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyW9y6/xJxvc.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyWxJ6/ZNk7Y.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyWkUr/eYUdI.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyWyOW/15bqWZ.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:603
            ,cid:4
            ,title:'诺兰蓝蝶充电震动按摩棒 特惠'
            ,volume:83
            ,recentvolume:34
            ,org_price:998
            ,price:299.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkGKGVd/tJjuk.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkGpcz9/kPxxj.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkGL0FH/Xx2Ni.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkGLcqM/NKxKg.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DOkGqbgF/w6SxG.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkGMobQ/bCSdd.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkGMjAH/Gnw6u.gif'
                ,'http://pic.yupoo.com/yige2002/DOkGMv9i/UYh6b.gif'
                ,'http://pic.yupoo.com/yige2002/DOkGrrIY/g6AeB.gif'
                ,'http://pic.yupoo.com/yige2002/DOkGrLBM/Xhlkq.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkGOT7s/aqDxv.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:604
            ,cid:4
            ,title:'香港诺兰伊杜 纯金属按摩棒 特惠'
            ,volume:81
            ,recentvolume:23
            ,org_price:998
            ,price:199.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkHPY6N/Tjeyx.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkHQ5FR/Rugy1.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHQqTL/sMRVN.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHQlyf/ZBDzy.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DOkHQJ4h/uvccf.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHQxWL/DhiGy.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHQNPg/xGVv5.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHvf2a/HylIR.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHQJlc/vH3Tw.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHvtDl/rkF6u.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRjQP/HUa0Y.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRecL/D8CCK.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRiRS/bi8iB.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRz6n/ATwbI.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRKNe/pvOtz.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRTgg/JyOFU.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHPWi6/325zn.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:605
            ,cid:4
            ,title:'香港诺兰月牙弯全球首创无线触感按摩棒手指触控智能按摩器 特惠'
            ,volume:91
            ,recentvolume:13
            ,org_price:998
            ,price:299.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkIFHxO/13jJEd.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkIG1Jo/QP2Nh.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkIl0vF/fDZQS.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkIlfOp/d7ZrY.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUvmaiU/1zUHH.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvmxNX/oygSQ.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvnxr2/L15Zz.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvmOru/ZywsJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvd7Ll/pQE0O.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvo6JM/zopxA.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvoCBO/jWxrl.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvp6pY/7BhRV.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvqeEi/4lah6.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvqv5V/fEmST.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvg1Ue/OZCUc.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvrG8k/5B77h.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvrcov/U98he.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvrBiI/T98eT.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvb9o9/QkTd2.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:606
            ,cid:4
            ,title:'诺兰AV棒震动按摩棒悦魅女用自慰器具成人用品 樱桃红 特惠'
            ,volume:68
            ,recentvolume:24
            ,org_price:998
            ,price:499.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkJ2RVm/PSNLz.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkJ2T47/13PLUx.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkJ3iYo/LvrJc.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkJ3x6V/LrsV.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUvOrWA/eg4vp.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvZq0z/bNzrQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw0nGA/Qg6Mt.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw0vAm/nguQG.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvQh6D/iOoHH.gif'
                ,'http://pic.yupoo.com/yige2002/DRUw14Wd/49rsH.gif'
                ,'http://pic.yupoo.com/yige2002/DRUw1ovt/TrnHW.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw21FG/jG0lw.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw2UqZ/TC4qt.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw33EN/Grqld.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw3gGg/oxAJT.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw4FdB/10sCYo.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw58FC/6AAuR.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvUDH6/wL8z0.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw6gtu/i24u1.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvYUw4/iXSv1.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:607
            ,cid:4
            ,title:'积之美 成人情趣用品 孔雀开屏前后通用多点刺激棒'
            ,volume:62
            ,recentvolume:32
            ,org_price:218
            ,price:78.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkJ5TIS/oBXtQ.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkJ65xM/u4XyT.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkJrHcC/K8cQS.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkJrR72/15uMdu.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUwArGM/zGWS9.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwq13X/14Zqtg.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwqebR/n4rFV.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwqmwq/TtjzU.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwBbo9/rIEK.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwBaIk/2s2pv.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwBjaO/aQ37Y.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:609
            ,cid:4
            ,title:'雷霆炫动充电AV棒女用阴蒂刺激乳头震动按摩棒'
            ,volume:48
            ,recentvolume:16
            ,org_price:298
            ,price:98.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DVI0EuPO/42OcH.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DVI0Esfs/Y4MAV.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0EENq/75WwC.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0FR5x/otMoi.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DVI0dGup/gma42.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0GbjR/dY4IH.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0GFFa/pgjIk.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0GP3z/CLmje.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0GYD4/FAOqd.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0HuAZ/h00Cg.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0HwqZ/IMnyX.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0IYU3/Td4tr.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0I4Sm/3uzyg.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0gGG8/N2gaJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0IRcO/GOdRX.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0JhdD/Dv1Ld.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0hMIX/PC7gq.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0i3eB/Hn0nb.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0Li75/e1VpF.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0LnIC/xHtiJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI0jzno/OCggr.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:610
            ,cid:4
            ,title:'蒂贝蜜蝶戏珠高震力6频率转珠震动按摩棒'
            ,volume:48
            ,recentvolume:16
            ,org_price:298
            ,price:118.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DVI1D9Jd/OLdcb.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DVI1DjdD/RbiPV.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI1C9TN/Zl7M1.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DVI1Cjv2/iMyvV.gif'
                ,'http://pic.yupoo.com/yige2002/DVI1cSN9/wKb0h.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI1fDhy/gOGEH.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:611
            ,cid:4
            ,title:'激情美人鱼玉兔玉鸟转珠振动棒G点高潮必备'
            ,volume:48
            ,recentvolume:16
            ,org_price:228
            ,price:45.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DVI2elVv/8iZIg.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DVI2dBny/cHu3t.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI2dQLd/lwBtD.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI2dI0f/B2zTR.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DVI2ed9O/KJA2x.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI1N8KN/ikKYD.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI2hdVN/fuZtB.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI2ivRH/9avPk.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI2k2F6/3tPoC.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI2ketv/lBzpa.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI2kPZJ/MiVpU.gif'
                ,'http://pic.yupoo.com/yige2002/DVI2l2VV/9mpAi.gif'
                ,'http://pic.yupoo.com/yige2002/DVI2lS7c/fn4cK.gif'
                ,'http://pic.yupoo.com/yige2002/DVI2mgPt/bDWsY.gif'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:612
            ,cid:4
            ,title:'水晶阳具 激情四射的summer'
            ,volume:48
            ,recentvolume:16
            ,org_price:156
            ,price:30.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DVI2un7m/W5Chr.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DVI2WH2m/itNCh.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI2Xe1u/m5hrM.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI2X9ZB/4RF9y.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DVI306qq/vAwNy.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI2ZV3q/1243oX.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:613
            ,cid:4
            ,title:'蒂贝跳蛋家族总有一款属于你'
            ,volume:48
            ,recentvolume:16
            ,org_price:429.00
            ,price:79.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYe9El1u/12I0oV.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYe9EVl4/ZJC8n.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe9F8yX/Ltr8j.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe9HKXN/ssSgj.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYe9EQQk/a1Lv2.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe9FyjU/mPD4J.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe9FLnd/ug1N8.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe9FOKh/14UuTu.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe9FlBM/VfJZY.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:614
            ,cid:4
            ,title:'爱情教练缩阴器 阴道收缩缩阴棒缩阴栓缩阴丹美容性用品'
            ,volume:48
            ,recentvolume:16
            ,org_price:268.00
            ,price:100.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYeacH7o/bK3y0.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYea0EL4/H29Yg.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeadaSc/2RtHV.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYeadrBn/VpHY9.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeadKRh/inXTM.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeae0S8/7K5s5.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeaeNQW/KgbnP.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeaf6H4/epOSp.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeagcv4/4VvwM.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeagrVr/97W2p.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeaj7Vj/G1N2t.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeagaOx/tvyvl.jpg'
                ,'http://pic.yupoo.com/yige2002/DYea4ptt/hx7A4.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeah3pu/nGEVv.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeagAY1/409bC.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeahqBq/SRclm.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeahLJd/3B9P5.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeakmIW/YiJMJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeactvP/HA3kS.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:615
            ,cid:4
            ,title:'闺趣AV棒 女用器具自慰按摩棒'
            ,volume:48
            ,recentvolume:16
            ,org_price:328.00
            ,price:118.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYeb5huC/59yo.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYeb2fVr/o97GS.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeb2ers/U8FUL.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYeb2vqs/RPFlM.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeb3pH8/QcdDZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeb3rIx/QE2Oz.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeb3p9o/m7dOl.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeb3JKz/Jb9A6.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeb33FV/p7McA.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeb4458/PMwAi.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:616
            ,cid:4
            ,title:'硅胶隐形文胸聚拢婚纱礼服游泳小胸加厚无痕拍照乳贴'
            ,volume:48
            ,recentvolume:16
            ,org_price:258.00
            ,price:58.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYecFoMF/5kpIB.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYecFB8F/rktUp.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYecI9tE/KzRle.jpg'
                ,'http://pic.yupoo.com/yige2002/DYecF5WF/4siTF.jpg'
                ,'http://pic.yupoo.com/yige2002/DYecFfZs/R6mPh.jpg'
                ,'http://pic.yupoo.com/yige2002/DYecG0Oj/BM3pE.jpg'
                ,'http://pic.yupoo.com/yige2002/DYecFXY6/LzcDw.jpg'
                ,'http://pic.yupoo.com/yige2002/DYecGbdD/Im10X.jpg'
                ,'http://pic.yupoo.com/yige2002/DYecGmn6/UkhBh.jpg'
                ,'http://pic.yupoo.com/yige2002/DYectZeQ/xI4yJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DYecGBJl/Brf3w.jpg'
                ,'http://pic.yupoo.com/yige2002/DYecG5wb/b8Yi8.jpg'
                ,'http://pic.yupoo.com/yige2002/DYecGRY4/hWqXc.jpg'
                ,'http://pic.yupoo.com/yige2002/DYecHBbW/bZUAT.jpg'
                ,'http://pic.yupoo.com/yige2002/DYecFhuG/8kgq6.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        {
            pid:617
            ,cid:4
            ,title:'百乐正品原野派极乐棒 30频震动 防水 高品质静音马达'
            ,volume:48
            ,recentvolume:16
            ,org_price:128.00
            ,price:68.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYed8ZYI/AS8qf.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYed9kyC/geBRv.jpg'
                ,'http://pic.yupoo.com/yige2002/DYedaaRg/LFX0M.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYed9Dn9/DfaJD.jpg'
                ,'http://pic.yupoo.com/yige2002/DYedaNMS/CILSk.jpg'
                ,'http://pic.yupoo.com/yige2002/DYedbUxk/UGYTG.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DVYBUlm8/c4Pvc.png'
                ,'http://pic.yupoo.com/yige2002/DVYBUJMc/Gk7l7.png'
                ,'http://pic.yupoo.com/yige2002/DVYBVKON/pdnE0.png'
                ,null
            ]
        },

        null
    ]