/**
 * Created by lishiming on 14-6-20.
 */
exports.productarr=
    [
        {
            pid:451
            ,cid:3
            ,title:'英国YouCups优客仕突破系列男用自慰杯飞机杯'
            ,volume:45
            ,recentvolume:14
            ,org_price:428.00
            ,price:168.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnSg5yh/Ng3ln.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnSjYbV/o4TJx.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSkTni/m2VI.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSl2HM/eHse2.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSkhva/rys7K.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUlYct8/m0aFq.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUm93TF/pO7dK.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUm9qwt/NxoBy.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUm9GI0/Rd1IW.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUm9PeW/12Ncgf.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUlZx15/H0R1p.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUma6Td/FZGxw.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUlZPAE/GBXjo.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmaEMs/zmUwb.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmaMGH/Cf7X9.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmb6a5/14Hfrg.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUlXrq5/6Wfxe.jpg'
                ,null
            ]
        },

        {
            pid:452
            ,cid:3
            ,title:'百乐BAILE 成人用品情趣用品 男用自慰器飞机杯系列推荐 旋转情人'
            ,volume:62
            ,recentvolume:9
            ,org_price:899
            ,price:499.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnSPu71/bDEPB.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnSLb1i/12IOpu.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSP4L0/C2oM.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSOXtG/5ewdY.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUmLZbS/BHLm1.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmBxB3/zJm6F.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmMoxc/EO3LR.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmNLmF/zczZF.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmNWQ6/pG1vg.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmOaGX/11hXub.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmOlE6/XY1Sa.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmOwDp/wqQ1C.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmOxyQ/TnfK5.jpg'
                ,null
            ]
        },

        {
            pid:453
            ,cid:3
            ,title:'水晶延时手指扣扣套环 简装软胶狼牙刺套 跳蛋增大套'
            ,volume:83
            ,recentvolume:31
            ,org_price:28.00
            ,price:9.9
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnTyewy/fnr8B.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnTzaW6/dIxi8.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnTyUek/dZ0M7.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnTz5cs/8HYGS.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUs3r3Z/3Arjg.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsdXjm/gRSIF.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsejVw/IjGuT.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsej69/111r0h.jpg'
                ,null
            ]
        },

        {
            pid:454
            ,cid:3
            ,title:'小名器真人阴臀倒模'
            ,volume:61
            ,recentvolume:24
            ,org_price:428.00
            ,price:168.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnU2teU/11UcTK.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnTYVxX/o8KFP.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnU2NgM/GFof0.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnU434u/HagOx.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUsELnd/FN6M2.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsPri3/QPcn0.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsQCyP/lWrcP.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsFoCh/7X2CI.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsPWEJ/UTq65.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsReov/KAPbo.jpg'
                ,null
            ]
        },

        {
            pid:455
            ,cid:3
            ,title:'一体式充气娃娃你心中最美的女神'
            ,volume:40
            ,recentvolume:12
            ,org_price:580.00
            ,price:230.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DRKOkNzK/de45M.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DRKOkOWd/umu31.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOlupU/wEwTI.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKObZql/OZSko.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRKOccAW/KdXZu.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOn51C/hXbCx.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOmpWA/K9Ewe.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOnQ5G/h1zRg.jpg'
                ,null
            ]
        },

        {
            pid:456
            ,cid:3
            ,title:'高级半实体充气娃娃女神就在你怀中'
            ,volume:16
            ,recentvolume:14
            ,org_price:380.00
            ,price:110.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DRKOX4MW/33aze.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DRKOX1KH/QZTsn.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOYanb/ns2B5.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRKONCXL/10b94n.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKONO9j/ls0S6.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOY0pB/upIJL.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOO8Zd/MBcwh.jpg'
                ,null
            ]
        },

        null
    ]