/**
 * Created by lishiming on 14-6-11.
 */
exports.productarr=
    [
        {
            pid:200
            ,cid:1
            ,title:'情趣内衣pid200媚火情趣内衣 无袖拼接网纱露背夜店服装 PU亮面性感睡裙 魅力惠'
            ,volume:51
            ,recentvolume:24
            ,org_price:98
            ,price:43.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkKLyHT/2XInj.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkKLMu1/CFN4.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkKLRTN/OTDzD.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkKq1TD/n18bL.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRU9FOuo/15aMy0.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU9Geaw/E2vEG.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU9w4zY/ZWwnp.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU9Igav/6CZUi.jpg'
                ,null
            ]
        },

        {
            pid:201
            ,cid:1
            ,title:'媚火情趣内衣 诱惑夜店装 性感睡衣超短裙紧身透明制服 魅力惠'
            ,volume:65
            ,recentvolume:23
            ,org_price:102
            ,price:58.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkLdDwZ/7zBIU.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkLdJ7M/iccUn.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLe96b/EsIwW.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLdYow/seDhm.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRU8W3zI/ek38h.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU8XFx6/10YukC.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU8YTm7/11KWrl.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU8YelQ/132Jlu.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU907DL/7997J.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU90wdV/v5TCC.jpg'
                ,null
            ]
        },

        {
            pid:202
            ,cid:1
            ,title:'媚火情趣内衣 夜店装惹火豹纹吊带制服套装 性感睡衣睡裙 魅力惠'
            ,volume:65
            ,recentvolume:32
            ,org_price:100
            ,price:46.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkLgeFY/P9AXD.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkLgmOJ/1279BD.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLCec4/sY9vU.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLCnD2/jm19I.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRU84YJO/8r7n6.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU86YIf/11i4wz.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU87Y7g/MX9O7.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU89WtF/X0O32.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU8aVJz/prAsx.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU8cNzK/oL0N0.jpg'
                ,null
            ]
        },

        {
            pid:203
            ,cid:1
            ,title:'媚火情趣内衣女诱惑夜店套装 性感睡衣短裙紧身钢管舞制服 魅力惠'
            ,volume:37
            ,recentvolume:12
            ,org_price:100
            ,price:44.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkLYQ0E/k3NrT.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkLZ5R9/mKbqq.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLZbQF/yNe4J.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLDDuH/orXXH.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRU7wMAv/HbXqd.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU7n0Tb/MH46l.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU7ytRx/O20lI.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU7Ad3n/Po7UQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU7BdGY/F5cHG.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU7qpNp/f0WXD.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU7CDZb/16JOj.jpg'
                ,null
            ]
        },

        {
            pid:204
            ,cid:1
            ,title:'媚火情趣内衣 夜店装惹火豹纹吊带制服套装 性感睡衣睡裙 魅力惠'
            ,volume:56
            ,recentvolume:21
            ,org_price:110
            ,price:57.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkMjq1H/Kvdcv.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkMjq4u/7qC17.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkMjw8d/KCAwh.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkMjSpp/ZsC4n.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRU71SoT/12l7oL.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU6SbVg/RY0MC.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU74BpD/VlL80.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU75sNP/rv9a3.jpg'
                ,null
            ]
        },

        {
            pid:205
            ,cid:1
            ,title:'媚火情趣内衣 亮片吊带时尚夜店服 性感火辣束身睡衣超短裙 魅力惠 头牌推荐'
            ,volume:43
            ,recentvolume:32
            ,org_price:105
            ,price:51.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkMlXga/Bg1ht.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkMHxnr/FI2Pk.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkMHxWV/i6QFM.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkMHKae/BkKHx.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRU6g73C/3ODm.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU6gx1d/LUCAN.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU6iwpT/tKxHh.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU6iSQz/I37Xz.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU6iT4X/OCVOx.jpg'
                ,'http://pic.yupoo.com/yige2002/DRU68R6K/2ocEf.jpg'
                ,null
            ]
        },

        {
            pid:206
            ,cid:1
            ,title:'新婚之夜女式情趣内衣可爱公主肚兜粉色诱惑性感蕾丝透视透明短裙'
            ,volume:31
            ,recentvolume:22
            ,org_price:48.00
            ,price:14.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DRGUZvPb/3ltsZ.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DRGUZoEY/rdHMT.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGUZxLq/RQxBV.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGUZFvl/ck8Mk.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRGUZGyT/GtvvR.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGUZUkQ/KTYSP.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGV0r2w/ZnlvT.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGV0yjw/kUfR5.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGV0k3w/10qvCt.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGV0O6N/SEhA6.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGV0zmU/vVGGn.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGV0AB7/JaIYX.jpg'
                ,null
            ]
        },

        {
            pid:207
            ,cid:1
            ,title:'DS夜店情趣内衣粉色性感护士装'
            ,volume:25
            ,recentvolume:14
            ,org_price:98.00
            ,price:38.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DRGVNvv3/EXI79.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DRGVNDpC/kFxpe.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGVNEkD/Blw8E.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRGVNUyc/4Ac5p.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGVO7HY/oSgQb.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGVOCGF/pSAir.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGVOomg/exueG.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGVORn2/kZ9mx.jpg'
                ,null
            ]
        },

        {
            pid:208
            ,cid:1
            ,title:'性感情趣开档丝袜 开档连裤袜 黑色诱惑'
            ,volume:31
            ,recentvolume:12
            ,org_price:29.00
            ,price:14.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DRGW9hnd/Zua1h.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DRGWjwMY/6pRzM.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGW9ytF/NdhIL.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGWjLKj/StYPA.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRGWkeR2/eFg9Q.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGWjZWL/v6oUT.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGWkdu3/10cdp2.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGWkl38/1KX3n.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGWaneq/rdtoO.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGWaudI/Cf70o.jpg'
                ,null
            ]
        },

        {
            pid:209
            ,cid:1
            ,title:'情趣内衣性感制服情趣套装学生装红格子学生服诱惑角色扮演'
            ,volume:43
            ,recentvolume:32
            ,org_price:65.00
            ,price:30.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DRGWOfPH/CqW6y.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DRGWE0yX/kRK4y.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRGWE8tB/YBRYM.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGWOnPt/Mp17V.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGWOv4K/Vruzq.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGWOZZF/VJSKi.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGWEFVV/LRT2P.jpg'
                ,null
            ]
        },

        {
            pid:210
            ,cid:1
            ,title:'粉色女佣服 大幅露背制服诱惑'
            ,volume:46
            ,recentvolume:17
            ,org_price:45.00
            ,price:20.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DRGXij6B/wTWXc.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DRGXinSB/q97vK.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGX8vJC/14e75e.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRGXiBye/i0eLV.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGXiOIb/1SwA0.jpg'
                ,null
            ]
        },

        {
            pid:211
            ,cid:1
            ,title:'彩条空姐制服学生情趣内衣诱惑套装大码束胸性感短裙'
            ,volume:50
            ,recentvolume:23
            ,org_price:100.00
            ,price:37.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DRGXGQ4f/VHW9o.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DRGXR5IU/TEEDy.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGXR984/tfs0K.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRGXRLzl/TD8tn.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGXRvQN/wwuYl.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGXRwTo/E8MxM.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGXS8il/dSCif.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGXRNdk/CX1Qw.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGXRWxz/oPZZO.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGXSc9L/bQaSp.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGXSdMJ/nsmVz.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGXSly6/zC6ks.jpg'
                ,'http://pic.yupoo.com/yige2002/DRGXSYey/14HRt6.jpg'
                ,null
            ]
        },

        null
    ]