/**
 * Created by lishiming on 14-6-11.
 */
exports.productarr=
    [
        {
            pid:351
            ,cid:2
            ,title:'延时喷剂SK战马白金版 男士用持久防早泄 情趣性爱成人用品 头牌推荐'
            ,volume:72
            ,recentvolume:37
            ,org_price:80
            ,price:30
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkNACYy/rpEgT.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkNAOFO/10ijJX.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkNfrqr/qNoGs.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkNAVh5/14HAO8.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUgSJBa/VBdq3.jpg'
                ,null
            ]
        },

        {
            pid:352
            ,cid:2
            ,title:'日本2H2D延时喷剂 男性防早泄持久非伟哥万艾可进口原液'
            ,volume:62
            ,recentvolume:25
            ,org_price:360
            ,price:162
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkRE6Pj/f5jKx.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkRDY47/JKP2o.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkREbbK/DiyO3.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkREF8A/guoH1.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUh8c15/KYAiD.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUhla1h/8xgZS.jpg'
                ,null
            ]
        },

        {
            pid:353
            ,cid:2
            ,title:'人初油 男性外用延时喷剂 持久神油 防早泄延长时间 15ml 成人用品人体润滑'
            ,volume:80
            ,recentvolume:37
            ,org_price:78
            ,price:28.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkS4wvv/eqU3Y.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkS4ODR/13xjOk.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkS4WGg/qenqq.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkS4Tum/orc8j.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUhJaI4/3XSaX.jpg'
                ,null
            ]
        },

        {
            pid:354
            ,cid:2
            ,title:'美国KEY O女性快感增强液'
            ,volume:51
            ,recentvolume:22
            ,org_price:182
            ,price:129.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkSy9mn/5XGeS.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkSxZCs/lIER6.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkSyfdN/ZyBR8.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkSymjS/kAwti.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUix3Gh/k8sY2.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUiHRE2/WNc1r.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUixn3x/oHMKG.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUiI9i1/cZcaQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUiJ2TH/PiMuU.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUiInN6/ylUTd.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUiJi24/JYEMB.jpg'
                ,null
            ]
        },

        {
            pid:355
            ,cid:2
            ,title:'雅润男用成人情趣性用品润滑剂润滑液润滑油 肛交'
            ,volume:66
            ,recentvolume:21
            ,org_price:20
            ,price:2.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkSXd5q/UApJ0.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkSXfxP/ZZUPN.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkSXHIH/pDPUb.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkSXWJl/11zlq.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUj9Slo/eQPA1.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUja27k/13DI7O.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUjd0cy/UXjZs.jpg'
                ,null
            ]
        },

        {
            pid:356
            ,cid:2
            ,title:'男露888男用中药延时喷剂非进口印度神油伟哥'
            ,volume:78
            ,recentvolume:31
            ,org_price:169
            ,price:55.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkT5QEz/Ley58.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkT5WLc/JrpAj.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkTrKrJ/7rnk8.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkTrXAy/14hhqI.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUjBsBT/TgkhE.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUjBN5G/8HUVm.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUjqUDN/sVPkY.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUjBAS7/MXUHv.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUjBXzZ/H2n0e.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUjBUTK/CdeL6.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUjCpxK/qgpKg.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUjDOmp/PV9m9.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUjDKmE/mIdVk.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUjE8MJ/V4X4G.jpg'
                ,null
            ]
        },

        {
            pid:357
            ,cid:2
            ,title:'本草堂喷剂外用持久防早泄不麻木保健用品滑 本草堂喷剂15ML'
            ,volume:65
            ,recentvolume:23
            ,org_price:100
            ,price:16.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkTPkUA/R1RUs.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkTPD0B/raZBq.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkTPKIz/jZvpS.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkTPRW8/2QtuM.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUkffFx/EsQro.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUk5xZ0/xSApZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUkh3lC/pXOAH.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUkk3ln/9PGp0.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUklBIc/vfMEV.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUkm1o1/fjJvH.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUknuEu/fyjRp.jpg'
                ,null
            ]
        },

        {
            pid:358
            ,cid:2
            ,title:'倍力乐 人体润滑剂 房事润滑剂 性爱润滑剂 成人情趣用品'
            ,volume:72
            ,recentvolume:27
            ,org_price:56
            ,price:10.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkUcjmO/lAMXS.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkV592j/1YalX.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkUc3bY/E5dtm.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkUcshm/RZ4VZ.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUkOug1/w7jQo.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUkEeVp/hbDha.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUkRU65/DcUe.jpg'
                ,null
            ]
        },

        null
    ]