/**
 * Created by lishiming on 14-6-10.
 */
exports.productarr=
    [

        {
            pid:5
            ,cid:1
            ,title:'百花天使 性感机车短裙野战必备 魅力惠'
            ,volume:60
            ,recentvolume:24
            ,org_price:46
            ,price:26.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3pEBdV/pT2h1.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHy3mgDj/g5VPn.jpg'
                ,'http://pic.yupoo.com/yige2002/DHy3mpSX/BFxvL.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHy3mEHZ/nx02l.jpg'
                ,'http://pic.yupoo.com/yige2002/DHy2JfMy/FPZGb.jpg'
                ,'http://pic.yupoo.com/yige2002/DHy3obyC/14Jcjx.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:9
            ,cid:1
            ,title:'百花天使 激情透视蕾丝花边挂脖吊带性感情趣内衣 魅力惠'
            ,volume:43
            ,recentvolume:22
            ,org_price:35
            ,price:21.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3pFLcZ/b4XSH.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHyfiJlA/wpz4H.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyfj81q/HDSsJ.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHyfjqR0/rWuZy.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyfjiuw/3ka99.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyfkeEK/QQTHl.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyfkksx/3nMYX.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyfkW20/oMhpq.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyfkOsu/14jf5c.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:10
            ,cid:1
            ,title:'百花天使 致命诱惑 侧开透视蕾丝薄纱睡裙 魅力惠'
            ,volume:44
            ,recentvolume:22
            ,org_price:49
            ,price:30
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3pFSwx/wMnYW.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHyhe7zN/cgYU0.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyheynk/KkHLo.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHygA5yv/u41y2.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyhf4eZ/apwKd.jpg'
                ,'http://pic.yupoo.com/yige2002/DHygAv1Q/10T2oL.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyhfqWB/4go9r.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyhfU7x/Qs0kI.jpg'
                ,'http://pic.yupoo.com/yige2002/DHygBoIA/npx0x.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:11
            ,cid:1
            ,title:'百花天使 蕾丝花边透明性感睡裙诱惑睡衣 魅力惠'
            ,volume:66
            ,recentvolume:24
            ,org_price:49
            ,price:30
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3pFiaf/K3snU.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHyj0Qv4/H4n5J.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyj1ja3/3NS4S.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHyj1zgl/uJ8UZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyj27zt/Ym8ve.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyins8M/L1Btg.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyj26ql/14Qp6R.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyj2CaA/ik7Fl.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:15
            ,cid:1
            ,title:'百花天使黑红透明比基尼三点式 魅力惠'
            ,volume:45
            ,recentvolume:12
            ,org_price:36
            ,price:21.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOgfvuGY/rav5G.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOgfvFg2/GRpWg.jpg'
                ,'http://pic.yupoo.com/yige2002/DOgfvxxr/wqhyT.jpg'
                ,'http://pic.yupoo.com/yige2002/DOgfwpNX/hPK7K.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DOgfwLDL/pn6s7.jpg'
                ,'http://pic.yupoo.com/yige2002/DOgfxgge/N7KGV.jpg'
                ,'http://pic.yupoo.com/yige2002/DOgfybRM/11NHA8.jpg'
                ,'http://pic.yupoo.com/yige2002/DOgfzdxn/kgsRU.jpg'
                ,'http://pic.yupoo.com/yige2002/DOgfzIQ0/vND7.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:19
            ,cid:1
            ,title:'百花天使良家超长性感情趣睡袍 魅力惠'
            ,volume:63
            ,recentvolume:41
            ,org_price:40
            ,price:30
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3pHmHz/AEcgA.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHyzSdV7/LsWNk.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyzSEZU/H62pJ.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHyzSXzH/CLFyG.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyzeM0e/EgG27.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyzUl5Z/NiEJq.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyzVrBM/13nIrR.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyzWrzo/mIBL1.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyzX1Tb/aLfu7.jpg'
                ,'http://pic.yupoo.com/yige2002/DHyziTWR/B0NAi.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        null
    ]
