/**
 * Created by lishiming on 14-6-11.
 */
exports.productarr=
    [
        {
            pid:751
            ,cid:5
            ,title:'名流避孕套 活力螺纹+动感颗粒+柔滑丝薄 共30只正品安全套 震撼来临'
            ,volume:30
            ,recentvolume:10
            ,org_price:78
            ,price:23.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DNrwTsAn/RWb8L.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DKJgxSHE/OPI9L.jpg'
                ,'http://pic.yupoo.com/yige2002/DKJgLwg3/OP7qj.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DKJgI2JP/OjksK.jpg'
                ,'http://pic.yupoo.com/yige2002/DKJgMcn2/MLBMJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DKJgCzhw/Gaofr.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfn4OH/anaLj.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGCyv/WQZbB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGVwj/BaWlq.png'
                ,null
            ]
        },

        {
            pid:752
            ,cid:5
            ,title:'003超薄白金3片+黄金6片98  白金3片 38  黄金6片 65 全年最低'
            ,volume:51
            ,recentvolume:21
            ,org_price:157
            ,price:45.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DNrx7pEN/aPpEm.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DKPYuWPo/NrmUI.jpg'
                ,'http://pic.yupoo.com/yige2002/DKPYv4Je/Zazm5.jpg'
                ,'http://pic.yupoo.com/yige2002/DKPYv5qg/cY1Hd.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DKPYvmmJ/Obb2O.jpg'
                ,'http://pic.yupoo.com/yige2002/DKPYvqbh/mnEEL.jpg'
                ,'http://pic.yupoo.com/yige2002/DKPYvHHO/5lYZc.jpg'
                ,'http://pic.yupoo.com/yige2002/DKPYuE66/skpK9.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfn4OH/anaLj.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGCyv/WQZbB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGVwj/BaWlq.png'
                ,null
            ]
        },

        {
            pid:753
            ,cid:5
            ,title:'第六感原装进口避孕套72只 安全套 六合一24+螺纹24+超薄平滑24 震撼来临'
            ,volume:58
            ,recentvolume:21
            ,org_price:109
            ,price:70.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DNry1n8W/dXHsN.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DKSyjWif/6iESD.jpg'
                ,'http://pic.yupoo.com/yige2002/DKSyiY6q/xoXNG.jpg'
                ,'http://pic.yupoo.com/yige2002/DKSyiUc2/wKEJb.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DKSyjuUY/7grHb.jpg'
                ,'http://pic.yupoo.com/yige2002/DKSyjux8/dYEFm.jpg'
                ,'http://pic.yupoo.com/yige2002/DKSyeHZG/HjSn8.jpg'
                ,'http://pic.yupoo.com/yige2002/DKSykbkM/fjegP.jpg'
                ,'http://pic.yupoo.com/yige2002/DKSyjPWZ/xkRI0.jpg'
                ,'http://pic.yupoo.com/yige2002/DKSyi5fm/YhLk2.jpg'
                ,'http://pic.yupoo.com/yige2002/DKSyicXW/JFX6J.jpg'
                ,'http://pic.yupoo.com/yige2002/DKSyibtA/svtpe.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfn4OH/anaLj.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGCyv/WQZbB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGVwj/BaWlq.png'
                ,null
            ]
        },

        {
            pid:754
            ,cid:5
            ,title:'正品杜蕾斯超薄避孕套单片装'
            ,volume:58
            ,recentvolume:21
            ,org_price:4
            ,price:1.50
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DXwLRIXz/Ce7HP.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DXwLSAvU/iaWRI.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwLRP7B/zBU6E.jpg'
                ,'http://pic.yupoo.com/yige2002/DKSyiUc2/wKEJb.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DXwLRW4z/hzU45.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwLS329/11Ry7u.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwLSpWp/jLECT.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwLSx0s/o9mEC.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwLh1cM/TPT1R.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwLSOz0/hDuy4.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwLhiGn/rs6oI.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwLSND1/k4uMc.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwLTNVw/qqpqj.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwLU0EQ/zJiVo.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfn4OH/anaLj.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGCyv/WQZbB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGVwj/BaWlq.png'
                ,null
            ]
        },

        {
            pid:755
            ,cid:5
            ,title:'杜蕾斯心形铁盒钥匙扣安全套避孕套'
            ,volume:58
            ,recentvolume:21
            ,org_price:15
            ,price:6.50
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DXwM2ttZ/ocGI1.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DXwM2BCd/puc5M.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwM2Ioe/VeVHI.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DXwMF4E1/S9BU.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwMFcAa/nESb5.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwMEvji/ToAxA.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwMEUkl/edBRz.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwMF5xt/hA2K8.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwMFdMp/DXZ2H.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwMF5xM/E3Zm5.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfn4OH/anaLj.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGCyv/WQZbB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGVwj/BaWlq.png'
                ,null
            ]
        },

        {
            pid:756
            ,cid:5
            ,title:'巧克力避孕套礼物 最新创意情侣礼品 6颗杜蕾斯'
            ,volume:58
            ,recentvolume:21
            ,org_price:99
            ,price:38.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DXwQ4qsP/MLB3A.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DXwQ4LrC/1KbY.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwPtf2M/GEGFB.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DXwQ4WeU/6Gzcp.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwQ5I8R/151tRj.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwQ5aYy/GDIX2.jpg'
                ,'http://pic.yupoo.com/yige2002/DXwQ524l/Z2LI5.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfn4OH/anaLj.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGCyv/WQZbB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGVwj/BaWlq.png'
                ,null
            ]
        },

        {
            pid:757
            ,cid:5
            ,title:'杰士邦超薄家族 震撼来临'
            ,volume:58
            ,recentvolume:21
            ,org_price:77.00
            ,price:20.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYegufJA/Ufjow.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYegutud/KPcnz.jpg'
                ,'http://pic.yupoo.com/yige2002/DYegx5hu/1nL2y.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYegtTfB/tNCPr.jpg'
                ,'http://pic.yupoo.com/yige2002/DYegud8k/CTXuk.jpg'
                ,'http://pic.yupoo.com/yige2002/DYegvnIB/r3WqD.jpg'
                ,'http://pic.yupoo.com/yige2002/DYegwic4/123l1u.jpg'
                ,'http://pic.yupoo.com/yige2002/DYegwcal/14wQyd.jpg'
                ,'http://pic.yupoo.com/yige2002/DYegvSlh/8OJAq.jpg'
                ,'http://pic.yupoo.com/yige2002/DYegwJYJ/cnmPf.jpg'
                ,'http://pic.yupoo.com/yige2002/DYegwNIL/YUJad.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfn4OH/anaLj.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGCyv/WQZbB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGVwj/BaWlq.png'
                ,null
            ]
        },

        {
            pid:758
            ,cid:5
            ,title:'EVE避轻松液体安全套 震撼来临'
            ,volume:58
            ,recentvolume:21
            ,org_price:35.00
            ,price:10.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYeh3pcA/XdBsC.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYeh6abu/JbiQ8.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeh2UlO/14VXjF.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYeh3bnc/iqDWq.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeh40Ke/QznLf.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeh41IA/QG9DN.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeh3YcX/dbEdU.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeh4b27/sN4ZG.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeh4ofL/5eI5.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeh6ZDS/SOXNH.jpg'
                ,'http://pic.yupoo.com/yige2002/DYeh3RFE/6tZZc.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfn4OH/anaLj.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGCyv/WQZbB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGVwj/BaWlq.png'
                ,null
            ]
        },

        {
            pid:759
            ,cid:5
            ,title:'斯香妮狼牙套变形金刚虎牙套 头牌推荐 全年最低 震撼来临'
            ,volume:58
            ,recentvolume:21
            ,org_price:56.00
            ,price:9.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYehjAZo/P9dEV.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYehw6JQ/exxFC.jpg'
                ,'http://pic.yupoo.com/yige2002/DYehwvRa/b42br.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYehxQFI/KIL5v.jpg'
                ,'http://pic.yupoo.com/yige2002/DYehyL4K/Zp3m9.jpg'
                ,'http://pic.yupoo.com/yige2002/DYehyZQB/HI9Sp.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfn4OH/anaLj.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGCyv/WQZbB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGVwj/BaWlq.png'
                ,null
            ]
        },

        {
            pid:760
            ,cid:5
            ,title:'尚牌持久八合一超薄颗粒冰爽果味尖 超薄004单罐装'
            ,volume:58
            ,recentvolume:21
            ,org_price:89.00
            ,price:39.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/EfRAyv2X/vXh7d.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/EfRAySr9/gJTnW.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAyYQz/14Tbmc.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAyWMH/GcWHd.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/EfRAz0JI/WmO2M.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAzbPr/bvWdU.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAz0Zx/VKSiA.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAzvdx/h4xk5.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAzBYJ/Ui7mh.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAkxwX/15Dp5j.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAAd0C/Dxmc8.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAAj6d/MfwmA.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAA4s0/5KwYp.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAA9BN/X1AB5.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRAAgmy/ZpqjP.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfn4OH/anaLj.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGCyv/WQZbB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfGVwj/BaWlq.png'
                ,null
            ]
        },

        null
    ]