/**
 * Created by lishiming on 14-6-20.
 */
exports.productarr=
    [
        {
            pid:451
            ,cid:3
            ,title:'英国YouCups优客仕突破系列男用自慰杯飞机杯'
            ,volume:45
            ,recentvolume:14
            ,org_price:428.00
            ,price:168.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnSg5yh/Ng3ln.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnSjYbV/o4TJx.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSkTni/m2VI.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSl2HM/eHse2.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSkhva/rys7K.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUlYct8/m0aFq.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUm93TF/pO7dK.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUm9qwt/NxoBy.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUm9GI0/Rd1IW.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUm9PeW/12Ncgf.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUlZx15/H0R1p.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUma6Td/FZGxw.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUlZPAE/GBXjo.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmaEMs/zmUwb.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmaMGH/Cf7X9.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmb6a5/14Hfrg.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUlXrq5/6Wfxe.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:452
            ,cid:3
            ,title:'百乐BAILE 成人用品情趣用品 男用自慰器飞机杯系列推荐 旋转情人'
            ,volume:62
            ,recentvolume:9
            ,org_price:899
            ,price:499.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnSPu71/bDEPB.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnSLb1i/12IOpu.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSP4L0/C2oM.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSOXtG/5ewdY.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUmLZbS/BHLm1.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmBxB3/zJm6F.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmMoxc/EO3LR.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmNLmF/zczZF.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmNWQ6/pG1vg.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmOaGX/11hXub.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmOlE6/XY1Sa.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmOwDp/wqQ1C.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUmOxyQ/TnfK5.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:453
            ,cid:3
            ,title:'水晶延时手指扣扣套环 简装软胶狼牙刺套 跳蛋增大套'
            ,volume:83
            ,recentvolume:31
            ,org_price:28.00
            ,price:9.9
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnTyewy/fnr8B.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnTzaW6/dIxi8.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnTyUek/dZ0M7.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnTz5cs/8HYGS.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUs3r3Z/3Arjg.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsdXjm/gRSIF.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsejVw/IjGuT.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsej69/111r0h.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:454
            ,cid:3
            ,title:'小名器真人阴臀倒模'
            ,volume:61
            ,recentvolume:24
            ,org_price:36.00
            ,price:9.90
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnU2teU/11UcTK.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnTYVxX/o8KFP.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnU2NgM/GFof0.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnU434u/HagOx.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUsELnd/FN6M2.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsPri3/QPcn0.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsQCyP/lWrcP.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsFoCh/7X2CI.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsPWEJ/UTq65.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUsReov/KAPbo.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:455
            ,cid:3
            ,title:'一体式充气娃娃你心中最美的女神 国庆特惠 头牌推荐 光棍节'
            ,volume:40
            ,recentvolume:12
            ,org_price:580.00
            ,price:230.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DRKOkNzK/de45M.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DRKOkOWd/umu31.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOlupU/wEwTI.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKObZql/OZSko.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRKOccAW/KdXZu.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOn51C/hXbCx.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOmpWA/K9Ewe.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOnQ5G/h1zRg.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DXadcF2b/aduQB.jpg'
                ,'http://pic.yupoo.com/yige2002/DXadNZKp/4HrR0.jpg'
                ,'http://pic.yupoo.com/yige2002/DXadOwWu/A7ByF.jpg'
                ,null
            ]
        },

        {
            pid:456
            ,cid:3
            ,title:'高级半实体充气娃娃女神就在你怀中 光棍节 全年最低'
            ,volume:16
            ,recentvolume:14
            ,org_price:380.00
            ,price:110.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DRKOX4MW/33aze.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DRKOX1KH/QZTsn.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOYanb/ns2B5.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRKONCXL/10b94n.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKONO9j/ls0S6.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOY0pB/upIJL.jpg'
                ,'http://pic.yupoo.com/yige2002/DRKOO8Zd/MBcwh.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:460
            ,cid:3
            ,title:'玩爆潮品4D黑腔名器 真人女优处女阴道阴臀倒模飞机杯'
            ,volume:16
            ,recentvolume:14
            ,org_price:168.00
            ,price:40.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/EbytSH8k/HIaOZ.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DVI8POSR/J71wr.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8PZ7C/lnVEH.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8QucU/ei3tO.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8RXm2/DMrn1.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8RtAb/108ZN0.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8RIvc/oocpV.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DVI8TbCM/E2R3k.gif'
                ,'http://pic.yupoo.com/yige2002/DVI8UB1i/10fTgB.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8UUO4/PIJqn.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8UwkD/tPadj.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8sIFT/Lgrsf.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8VdPS/I7Dq3.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8Vvih/rah8F.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8W7sD/cznNu.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI8XBVc/5OfpS.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:457
            ,cid:3
            ,title:'日本NPG名器证明001小泽玛利亚真人阴臀倒模男用自慰器 光棍节'
            ,volume:16
            ,recentvolume:14
            ,org_price:300.00
            ,price:44.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DVI4n64m/12Sagq.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DVI4m5mN/XJxZJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI4mFw0/xwcK3.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DVI4ocLf/xnPP.gif'
                ,'http://pic.yupoo.com/yige2002/DVI4om2m/VA4Fn.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI4npj0/12RVgA.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI4nrbs/lsNmh.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI4nqLm/eW0DQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI3XwG0/QWC1B.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:458
            ,cid:3
            ,title:'中国第一裸 张筱雨名器 光棍节'
            ,volume:16
            ,recentvolume:14
            ,org_price:300.00
            ,price:44.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DVI6rw4g/N2Pqa.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DVI6TIYC/pYYqZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI6Vbxw/gLAu.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DVI6VoEF/XRN1R.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI6VAMB/KGHKl.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI6swjp/N2t8.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI6W2b4/EPMSB.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI6Vlvb/u82xK.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI6YnE4/Q9Tlh.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:459
            ,cid:3
            ,title:'日本NPG名器证明006颜如忆 阴部倒模 光棍节'
            ,volume:16
            ,recentvolume:14
            ,org_price:300.00
            ,price:44.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DVI7RHmY/LSKFH.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DVI7RTqr/t1pyK.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7ScKz/qkbBO.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DVI7S5cN/m2rKu.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7UmXT/7Mdmp.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7TwpJ/KOBvf.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7Vdmm/xa4FH.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7UoET/vfhon.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7UI0E/10Ywlq.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7UDKH/igoaq.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7V7T7/14IqRd.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7WbyT/FfdoS.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7VnPn/GqJmC.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7VqH1/e4Iw2.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7tjdg/nRY9q.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7Vqss/147rVz.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7WSaV/jhuiw.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7VTZh/JqmFj.jpg'
                ,'http://pic.yupoo.com/yige2002/DVI7X5ki/105LAK.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:461
            ,cid:3
            ,title:'优客仕浪语吟声电动男士熟女男自慰逼真电动阴道飞机杯 光棍节 全年最低'
            ,volume:16
            ,recentvolume:14
            ,org_price:299.00
            ,price:198.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYe3uiFU/LJyzw.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYe3vavr/FBd9e.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3vt0N/14qUrZ.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYe3vsfF/6CUBc.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3vCjA/tXY7S.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3vIXA/12u9Ht.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3vhDh/9gnak.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3w4qm/7Dia4.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3w8kk/QOOsH.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3wlWC/Qa2cE.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3vKlg/xVPQ5.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3vX8X/BEkQa.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3xwJW/15pinm.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3l3qK/Uu057.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3xGwi/IdDGH.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3xd7d/ysXN9.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3xnkn/azcEM.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3y90Y/91D3b.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3yjIs/TthHL.jpg'
                ,'http://pic.yupoo.com/yige2002/DYe3uiJZ/tStWV.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:462
            ,cid:3
            ,title:'吸附式飞机杯 边看边玩3D国模通道飞机杯 光棍节 全年最低'
            ,volume:16
            ,recentvolume:14
            ,org_price:599.00
            ,price:199.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/E8EuOD7W/IPkPa.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/E8EuPrYO/9qXNs.jpg'
                ,'http://pic.yupoo.com/yige2002/E8EuQ4GA/JVPz6.jpg'
                ,'http://pic.yupoo.com/yige2002/E8EuQcKs/SOXFA.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/E8EuPvFe/Ta19f.jpg'
                ,'http://pic.yupoo.com/yige2002/E8EuPhPq/zbhE0.jpg'
                ,'http://pic.yupoo.com/yige2002/E8EuPNas/64z5G.jpg'
                ,'http://pic.yupoo.com/yige2002/E8EuPzVN/uSg7Z.jpg'
                ,'http://pic.yupoo.com/yige2002/E8EuQ48z/K1c1k.jpg'
                ,'http://pic.yupoo.com/yige2002/E8EuQnmj/3uEjA.jpg'
                ,'http://pic.yupoo.com/yige2002/E8EuQq9x/DuZiM.jpg'
                ,'http://pic.yupoo.com/yige2002/E8EuRopT/VOHiH.jpg'
                ,'http://pic.yupoo.com/yige2002/E8EuONmA/LOX3W.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:463
            ,cid:3
            ,title:'充气娃娃非实体娃娃男性自慰器 东方脸谱充气玩偶特价 光棍节'
            ,volume:16
            ,recentvolume:14
            ,org_price:180.00
            ,price:70.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/EbeOI64h/kcg3w.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/EbePIoIe/ICADW.jpg'
                ,'http://pic.yupoo.com/yige2002/EbePIdhl/NaSOG.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/EbePIOq5/5nEd7.jpg'
                ,'http://pic.yupoo.com/yige2002/EbePIXzA/8oCPp.jpg'
                ,'http://pic.yupoo.com/yige2002/EbePJf3M/vEUQI.jpg'
                ,'http://pic.yupoo.com/yige2002/EbePJgxB/uumLF.jpg'
                ,'http://pic.yupoo.com/yige2002/EbePKeUi/14kGDT.jpg'
                ,'http://pic.yupoo.com/yige2002/EbePJAem/pjJbH.jpg'
                ,'http://pic.yupoo.com/yige2002/EbePJpXJ/UFbRj.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:464
            ,cid:3
            ,title:'JOKERC型包皮阻复环矫正器假性包茎包皮过长阻复环切器延时男用'
            ,volume:16
            ,recentvolume:14
            ,org_price:428.00
            ,price:168.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/EfRBwgZF/WsBhB.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/EfRBwcNe/UyWBT.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBwnEP/gk1o3.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBwGzT/ducxb.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/EfRBhxws/pWkwi.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBwXDL/10SVhI.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBwTH3/7ccqN.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBx5Gr/owyMc.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBxzAM/zQ7vZ.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBxdXU/3WsBc.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBxwxC/XjWL3.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBioTB/VPGpB.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBiv7E/112Edj.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBxX4u/BI4xp.jpg'
                ,'http://pic.yupoo.com/yige2002/EfRBxYg6/1nXqX.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        null
    ]