/**
 * Created by lishiming on 14-6-11.
 */
exports.productarr=
    [
        {
            pid:101
            ,cid:6
            ,title:'倍力乐销魂掌 全能调情手套 按摩潮吹 女用助情自慰 前戏情趣用品 头牌推荐'
            ,volume:51
            ,recentvolume:21
            ,org_price:38
            ,price:23.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VNLIB/9UBMs.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH6j6OLv/v056K.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6jJQuY/vtiqy.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6jKrRt/Cxll0.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6jKLZu/JGTyl.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6jL6Qf/QP6n8.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHYzDOoq/gOhx7.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYyX6u5/44ls4.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYzEkDI/XYNxn.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYyXiPd/okuaQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYzE7JM/kYtwQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYzEmo9/RYNcL.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYzEuEG/17mos.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYzErUI/BSBqP.jpg'
                ,'http://pic.yupoo.com/yige2002/DHpmq0sR/mRbfr.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYzEI4b/lCJB5.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYzEMNl/cmYXg.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYzELLu/9hfwY.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYzDYLZ/AoGTP.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:102
            ,cid:6
            ,title:'后庭塞 肛塞 肛门塞 拉珠 男用女用肛门自慰g点后庭情趣用品'
            ,volume:62
            ,recentvolume:24
            ,org_price:20
            ,price:10.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VO2As/WL7gw.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH6sliUj/10qGWZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6sn45q/HZCXo.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6slBbe/nHO9V.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHYiHnPj/4PHY.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYiHN8z/Qyaej.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYiHp6w/Fxbc2.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6snklb/vgFee.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6rJoF9/119TcF.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6rJG1h/2Fx2F.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6snu0a/8HbU.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6snllV/15s95g.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6snJuH/ax2mj.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:103
            ,cid:6
            ,title:'女用震动挑逗自慰情趣拉珠调情棒肛塞 G点后庭葫芦钻'
            ,volume:84
            ,recentvolume:31
            ,org_price:48
            ,price:23.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VNZkE/pcufV.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH6ySEVo/gFW7s.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6yUqzW/oXQMb.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6ygsFg/Kl4bA.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHYf4b9b/N9fyR.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYf4yqs/zNNP2.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYf4jpm/PPw1t.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYf4wzz/BiGmZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHYf41Zw/aYrQP.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6yTt23/13UJBz.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:104
            ,cid:6
            ,title:'成人情趣用品夫妻前戏调情白色透明夜光骰子筛子色子房事性爱助情'
            ,volume:45
            ,recentvolume:16
            ,org_price:9
            ,price:3.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VO9PY/XV8fE.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH6A4zaN/12ZzZa.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6AInL9/pAzUZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6AHjCX/ystC.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6AI8ca/6GYqc.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6AJd2c/10dayB.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHWQIp7v/G1yC9.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWQIoZH/oY6oK.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWQIETs/gn0ZV.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWQ1FAn/HNGzi.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWQI7ck/jCcvs.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6AInOG/pKO6e.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:105
            ,cid:6
            ,title:'正品 倍力乐威震天震震嘴 男女共用五种用法口交器'
            ,volume:91
            ,recentvolume:15
            ,org_price:280
            ,price:198
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VOLlz/CgLSl.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH6BRCEP/jLAkf.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BVtQ8/MPFKw.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BVhjA/64VvW.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DH6BT2LD/3V0Uh.png'
                ,'http://pic.yupoo.com/yige2002/DH6BTHgs/pCcvK.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BSZzj/CVzbK.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BU8iq/8ctua.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BTq4K/Cexcu.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BTmkH/TyYod.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWKi3nc/kIbEZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWKhUwO/CkzKF.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BVdx6/vKzEW.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BXoK4/CFKxj.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BXppZ/DQ9Ua.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BkVEf/SNOiS.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BlllS/V2iXC.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6BZOpe/vptmz.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6C0jYn/zxwdf.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWKhvXS/MQBmG.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:106
            ,cid:6
            ,title:'正品SEMO龙凤拉珠'
            ,volume:43
            ,recentvolume:20
            ,org_price:38
            ,price:22.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VOv2A/GFBuE.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH6CSjdY/F6XfA.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6DvTec/x0O9M.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6DAwrX/3olwO.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHWF2fvw/dN9Sc.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWF24ux/PF2R7.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWEl94L/5K2Q4.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6CZQij/tHIE5.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:107
            ,cid:6
            ,title:'正品蒂贝DIBE电动舌头口交器 变频震动棒跳蛋 女用自慰器具G点刺激棒'
            ,volume:87
            ,recentvolume:31
            ,org_price:158
            ,price:117.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VP45f/3M1Ls.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH6I2VRW/EZdfi.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6I1S9C/10P2Ws.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHWB8COr/rNJvO.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWBPp8i/ghWa1.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6HpKWn/Wp0AZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6I5lXi/oVq9z.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6I4NI3/J8BIi.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:108
            ,cid:6
            ,title:'玩爆潮品 硅胶拉珠女用后庭链肝门塞情趣用品成人玩具G点刺激棒 头牌推荐'
            ,volume:94
            ,recentvolume:16
            ,org_price:48
            ,price:23.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VOVpp/2VshK.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH6JzaHO/tYQpl.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6Jzzny/BYype.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6JywAj/6K9RQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6JzoTn/zyMcC.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6IWiNw/VUuH5.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6JAbis/7FEUw.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHWvdd9A/15Fd1F.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWvdDhw/BKgTI.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWvdy4u/reHbQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWvdEdR/P5Vhs.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWuwFNG/1Hsws.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWvdCyX/H8zkb.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWvdWgp/3GMhI.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWuwX31/xkybA.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWvdXtz/QO1f4.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:109
            ,cid:6
            ,title:'百乐正品振翅蝴蝶女用口交器吸水高潮不断情趣用品'
            ,volume:74
            ,recentvolume:23
            ,org_price:78
            ,price:43.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VNR0R/HBdck.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH6K15nb/15dN2B.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6Nj9K3/s29Yz.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6MFdGV/yY6DI.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHWldlTk/O4d6U.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6KFtu1/15kzr4.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWlUfX8/PGUni.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:110
            ,cid:6
            ,title:'百乐电击器 电动乳房胸部按摩贴 阴贴 情趣多功能电磁脉冲器'
            ,volume:20
            ,recentvolume:12
            ,org_price:100
            ,price:60
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VPqLy/1hNqL.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH6P6x0s/pLQkc.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DH6PJyHu/HeQmY.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:111
            ,cid:6
            ,title:'百乐电动假舌头舔吸阴蒂口交 情趣成人女用高潮吹刺激自慰性用器'
            ,volume:74
            ,recentvolume:30
            ,org_price:120
            ,price:82.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VPmet/13iHf2.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH6PP475/m14tS.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6QsW79/t1cwW.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6QsFaI/xzob2.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHWhYuFz/2yXgl.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWiFsqV/VfJOC.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6Qt9Va/15aadW.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6Qs9Rr/RjsO8.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6Qt8A8/8GwwJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6QtGUr/fW9jM.jpg'
                ,'http://pic.yupoo.com/yige2002/DHWiFhy6/KsZjJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DH6QsFaI/xzob2.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:112
            ,cid:6
            ,title:'百乐震动乳夹 前戏必备 男用女用自慰器 乳头刺激 电动乳房按摩器'
            ,volume:41
            ,recentvolume:31
            ,org_price:80
            ,price:54
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VPuKW/1EAPA.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH70DUx9/1378F8.jpg'
                ,'http://pic.yupoo.com/yige2002/DH70DnGk/15lwaA.jpg'
                ,'http://pic.yupoo.com/yige2002/DH70Egce/12dLc.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHW5g4bU/DqXkO.jpg'
                ,'http://pic.yupoo.com/yige2002/DHW5geq3/1ySyI.jpg'
                ,'http://pic.yupoo.com/yige2002/DH70DnGk/15lwaA.jpg'
                ,'http://pic.yupoo.com/yige2002/DHW5g9UK/ifMGr.jpg'
                ,'http://pic.yupoo.com/yige2002/DH700fVW/eRMQq.jpg'
                ,'http://pic.yupoo.com/yige2002/DH70CQxP/13NbhT.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:113
            ,cid:6
            ,title:'震动阴道窥视镜女用阴道内窥镜 窥阴器乐透镜 扩阴器情趣另类玩具'
            ,volume:51
            ,recentvolume:25
            ,org_price:138
            ,price:66
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VOTqt/suwXq.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH71kd5d/MV7pv.jpg'
                ,'http://pic.yupoo.com/yige2002/DH71ksZl/mn0mm.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHMYWGPK/w7ZX4.jpg'
                ,'http://pic.yupoo.com/yige2002/DHMYWBFa/zURrC.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        {
            pid:114
            ,cid:6
            ,title:'香港邦爱另类玩具sm情趣双峰震动乳夹女用品乳房头刺激自慰按摩器'
            ,volume:41
            ,recentvolume:8
            ,org_price:72
            ,price:58.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3VPJN8/IhhtS.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DH71Zisf/7Q09d.jpg'
                ,'http://pic.yupoo.com/yige2002/DH71YDlU/bB9J2.jpg'
                ,'http://pic.yupoo.com/yige2002/DH720szB/peqf7.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHMUFcp3/v83Yg.jpg'
                ,'http://pic.yupoo.com/yige2002/DHMUFrtI/jac7V.jpg'
                ,'http://pic.yupoo.com/yige2002/DHMUFA8u/QFQKJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHMUFIAr/EDsPr.jpg'
                ,'http://pic.yupoo.com/yige2002/DHMUFN9z/7WRrQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHMUFZSI/sSUo4.jpg'
                ,'http://pic.yupoo.com/yige2002/DHMUGfFo/RbT1Y.jpg'
                ,'http://pic.yupoo.com/yige2002/DHMUGg8h/5SuMz.jpg'
                ,null
            ]
            ,experience:
            [
                null
            ]
        },

        null
    ]