/**
 * Created by lishiming on 14-6-11.
 */
exports.productarr=
    [
        {
            pid:200
            ,cid:1
            ,title:'情趣内衣pid200媚火情趣内衣 无袖拼接网纱露背夜店服装 PU亮面性感睡裙 魅力惠'
            ,volume:51
            ,recentvolume:24
            ,org_price:98
            ,price:43.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkKLyHT/2XInj.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkKLMu1/CFN4.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkKLRTN/OTDzD.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkKq1TD/n18bL.jpg'
                ,null
            ]
            ,detailpics:
            [
                null
            ]
        },

        {
            pid:201
            ,cid:1
            ,title:'媚火情趣内衣 诱惑夜店装 性感睡衣超短裙紧身透明制服 魅力惠'
            ,volume:65
            ,recentvolume:23
            ,org_price:102
            ,price:58.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkLdDwZ/7zBIU.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkLdJ7M/iccUn.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLe96b/EsIwW.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLdYow/seDhm.jpg'
                ,null
            ]
            ,detailpics:
            [
                null
            ]
        },

        {
            pid:202
            ,cid:1
            ,title:'媚火情趣内衣 夜店装惹火豹纹吊带制服套装 性感睡衣睡裙 魅力惠'
            ,volume:65
            ,recentvolume:32
            ,org_price:100
            ,price:46.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkLgeFY/P9AXD.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkLgmOJ/1279BD.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLCec4/sY9vU.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLCnD2/jm19I.jpg'
                ,null
            ]
            ,detailpics:
            [
                null
            ]
        },

        {
            pid:203
            ,cid:1
            ,title:'媚火情趣内衣女诱惑夜店套装 性感睡衣短裙紧身钢管舞制服 魅力惠'
            ,volume:37
            ,recentvolume:12
            ,org_price:100
            ,price:44.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkLYQ0E/k3NrT.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkLZ5R9/mKbqq.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLZbQF/yNe4J.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkLDDuH/orXXH.jpg'
                ,null
            ]
            ,detailpics:
            [
                null
            ]
        },

        {
            pid:204
            ,cid:1
            ,title:'媚火情趣内衣 夜店装惹火豹纹吊带制服套装 性感睡衣睡裙 魅力惠'
            ,volume:56
            ,recentvolume:21
            ,org_price:110
            ,price:57.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkMjq1H/Kvdcv.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkMjq4u/7qC17.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkMjw8d/KCAwh.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkMjSpp/ZsC4n.jpg'
                ,null
            ]
            ,detailpics:
            [
                null
            ]
        },

        {
            pid:205
            ,cid:1
            ,title:'媚火情趣内衣 亮片吊带时尚夜店服 性感火辣束身睡衣超短裙 魅力惠 头牌推荐'
            ,volume:43
            ,recentvolume:32
            ,org_price:105
            ,price:51.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkMlXga/Bg1ht.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkMHxnr/FI2Pk.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkMHxWV/i6QFM.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkMHKae/BkKHx.jpg'
                ,null
            ]
            ,detailpics:
            [
                null
            ]
        },

        null
    ]