/**
 * Created by lishiming on 14-6-20.
 */
exports.productarr=
    [
        {
            pid:451
            ,cid:3
            ,title:'英国YouCups优客仕突破系列男用自慰杯飞机杯'
            ,volume:0
            ,recentvolume:0
            ,org_price:428.00
            ,price:168.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnSg5yh/Ng3ln.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnSjYbV/o4TJx.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSkTni/m2VI.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSl2HM/eHse2.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSkhva/rys7K.jpg'
                ,null
            ]
            ,detailpics:
            [
                null
            ]
        },

        {
            pid:452
            ,cid:3
            ,title:'百乐BAILE 成人用品情趣用品 男用自慰器飞机杯系列推荐 旋转情人'
            ,volume:0
            ,recentvolume:0
            ,org_price:899
            ,price:499.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnSPu71/bDEPB.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnSLb1i/12IOpu.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSP4L0/C2oM.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnSOXtG/5ewdY.jpg'
                ,null
            ]
            ,detailpics:
            [
                null
            ]
        },

        {
            pid:453
            ,cid:3
            ,title:'水晶延时手指扣扣套环 简装软胶狼牙刺套 跳蛋增大套'
            ,volume:0
            ,recentvolume:0
            ,org_price:28.00
            ,price:9.9
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnTyewy/fnr8B.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnTzaW6/dIxi8.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnTyUek/dZ0M7.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnTz5cs/8HYGS.jpg'
                ,null
            ]
            ,detailpics:
            [
                null
            ]
        },

        {
            pid:454
            ,cid:3
            ,title:'小名器真人阴臀倒模'
            ,volume:0
            ,recentvolume:0
            ,org_price:428.00
            ,price:168.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DQnU2teU/11UcTK.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DQnTYVxX/o8KFP.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnU2NgM/GFof0.jpg'
                ,'http://pic.yupoo.com/yige2002/DQnU434u/HagOx.jpg'
                ,null
            ]
            ,detailpics:
            [
                null
            ]
        },

        null
    ]