/**
 * Created by lishiming on 14-6-11.
 */
exports.productarr=
    [
        {
            pid:600
            ,cid:4
            ,title:'阴道哑铃 特惠'
            ,volume:72
            ,recentvolume:29
            ,org_price:299
            ,price:258.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DO6hmjUb/LADt7.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DO6hmbYG/TOPvf.jpg'
                ,'http://pic.yupoo.com/yige2002/DO6hlRs4/RBT2A.jpg'
                ,'http://pic.yupoo.com/yige2002/DO6hmprO/IrcG0.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUtUH4I/mwk1x.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtKtdi/skBGV.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtVfOl/dwiHn.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtKOcx/4bFIa.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtVC6D/fTd2T.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtVLh7/14R4sZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtVYdd/BUxMy.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtWTez/cYbqL.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtWlSL/eFgcB.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtWzNW/fC4qE.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtM40n/15rjDg.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtWSt9/HgiP.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtXfgJ/148cQX.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtX9yx/hh4cz.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtMRNL/11e4Tt.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtXENK/HmKxn.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtXRt1/PcC4y.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtZ72L/aPxig.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtZjhB/7CSEI.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtYDqG/J6l7w.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUtYCS4/AVbOh.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFggBZc/dPKey.png'
                ,'http://pic.yupoo.com/yige2002/DTFggJvJ/a492Q.png'
                ,'http://pic.yupoo.com/yige2002/DTFfXGkg/mTpKY.png'
                ,null
            ]
        },

        {
            pid:601
            ,cid:4
            ,title:'诺兰音乐人 特惠'
            ,volume:67
            ,recentvolume:18
            ,org_price:998
            ,price:399.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DO6iocFf/f6G0y.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DO6ino2O/121ieL.jpg'
                ,'http://pic.yupoo.com/yige2002/DO6i3Msk/uowfl.jpg'
                ,'http://pic.yupoo.com/yige2002/DO6inW9R/j7o26.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUuI4dE/9dF7u.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuJ4bt/8UyhD.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuJhAn/GVcjT.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuIXSO/zmqeN.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuK6Ge/hnfJL.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuMf1C/vlxoJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuOUx6/DTcsU.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuREpO/27hzu.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUuSUJT/pHLH3.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFggBZc/dPKey.png'
                ,'http://pic.yupoo.com/yige2002/DTFggJvJ/a492Q.png'
                ,'http://pic.yupoo.com/yige2002/DTFfXGkg/mTpKY.png'
                ,null
            ]
        },

        {
            pid:602
            ,cid:4
            ,title:'香港诺兰ELYI艾怡 金属迷你av震动按摩棒 特惠'
            ,volume:63
            ,recentvolume:24
            ,org_price:678
            ,price:356.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkyV3ch/7ByQB.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkyVsJn/wkEs.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyzVuN/HBwhB.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyVwDV/qTrcb.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DOkyAapq/ZLmDc.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyAhDK/IP3S9.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyVU5U/Id4tk.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyAy6L/kbRW5.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyW9y6/xJxvc.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyWxJ6/ZNk7Y.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyWkUr/eYUdI.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkyWyOW/15bqWZ.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFggBZc/dPKey.png'
                ,'http://pic.yupoo.com/yige2002/DTFggJvJ/a492Q.png'
                ,'http://pic.yupoo.com/yige2002/DTFfXGkg/mTpKY.png'
                ,null
            ]
        },

        {
            pid:603
            ,cid:4
            ,title:'诺兰蓝蝶充电震动按摩棒 特惠'
            ,volume:83
            ,recentvolume:34
            ,org_price:998
            ,price:299.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkGKGVd/tJjuk.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkGpcz9/kPxxj.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkGL0FH/Xx2Ni.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkGLcqM/NKxKg.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DOkGqbgF/w6SxG.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkGMobQ/bCSdd.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkGMjAH/Gnw6u.gif'
                ,'http://pic.yupoo.com/yige2002/DOkGMv9i/UYh6b.gif'
                ,'http://pic.yupoo.com/yige2002/DOkGrrIY/g6AeB.gif'
                ,'http://pic.yupoo.com/yige2002/DOkGrLBM/Xhlkq.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkGOT7s/aqDxv.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFggBZc/dPKey.png'
                ,'http://pic.yupoo.com/yige2002/DTFggJvJ/a492Q.png'
                ,'http://pic.yupoo.com/yige2002/DTFfXGkg/mTpKY.png'
                ,null
            ]
        },

        {
            pid:604
            ,cid:4
            ,title:'香港诺兰伊杜 纯金属按摩棒 特惠'
            ,volume:81
            ,recentvolume:23
            ,org_price:998
            ,price:199.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkHPY6N/Tjeyx.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkHQ5FR/Rugy1.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHQqTL/sMRVN.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHQlyf/ZBDzy.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DOkHQJ4h/uvccf.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHQxWL/DhiGy.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHQNPg/xGVv5.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHvf2a/HylIR.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHQJlc/vH3Tw.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHvtDl/rkF6u.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRjQP/HUa0Y.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRecL/D8CCK.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRiRS/bi8iB.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRz6n/ATwbI.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRKNe/pvOtz.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHRTgg/JyOFU.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkHPWi6/325zn.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFggBZc/dPKey.png'
                ,'http://pic.yupoo.com/yige2002/DTFggJvJ/a492Q.png'
                ,'http://pic.yupoo.com/yige2002/DTFfXGkg/mTpKY.png'
                ,null
            ]
        },

        {
            pid:605
            ,cid:4
            ,title:'香港诺兰月牙弯全球首创无线触感按摩棒手指触控智能按摩器 特惠'
            ,volume:91
            ,recentvolume:13
            ,org_price:998
            ,price:299.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkIFHxO/13jJEd.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkIG1Jo/QP2Nh.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkIl0vF/fDZQS.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkIlfOp/d7ZrY.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUvmaiU/1zUHH.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvmxNX/oygSQ.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvnxr2/L15Zz.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvmOru/ZywsJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvd7Ll/pQE0O.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvo6JM/zopxA.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvoCBO/jWxrl.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvp6pY/7BhRV.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvqeEi/4lah6.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvqv5V/fEmST.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvg1Ue/OZCUc.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvrG8k/5B77h.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvrcov/U98he.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvrBiI/T98eT.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvb9o9/QkTd2.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFggBZc/dPKey.png'
                ,'http://pic.yupoo.com/yige2002/DTFggJvJ/a492Q.png'
                ,'http://pic.yupoo.com/yige2002/DTFfXGkg/mTpKY.png'
                ,null
            ]
        },

        {
            pid:606
            ,cid:4
            ,title:'诺兰AV棒震动按摩棒悦魅女用自慰器具成人用品 樱桃红 特惠'
            ,volume:68
            ,recentvolume:24
            ,org_price:998
            ,price:499.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkJ2RVm/PSNLz.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkJ2T47/13PLUx.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkJ3iYo/LvrJc.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkJ3x6V/LrsV.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUvOrWA/eg4vp.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvZq0z/bNzrQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw0nGA/Qg6Mt.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw0vAm/nguQG.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvQh6D/iOoHH.gif'
                ,'http://pic.yupoo.com/yige2002/DRUw14Wd/49rsH.gif'
                ,'http://pic.yupoo.com/yige2002/DRUw1ovt/TrnHW.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw21FG/jG0lw.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw2UqZ/TC4qt.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw33EN/Grqld.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw3gGg/oxAJT.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw4FdB/10sCYo.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw58FC/6AAuR.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUvUDH6/wL8z0.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUw6gtu/i24u1.gif'
                ,'http://pic.yupoo.com/yige2002/DRUvYUw4/iXSv1.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFggBZc/dPKey.png'
                ,'http://pic.yupoo.com/yige2002/DTFggJvJ/a492Q.png'
                ,'http://pic.yupoo.com/yige2002/DTFfXGkg/mTpKY.png'
                ,null
            ]
        },

        {
            pid:607
            ,cid:4
            ,title:'积之美 成人情趣用品 孔雀开屏前后通用多点刺激棒'
            ,volume:62
            ,recentvolume:32
            ,org_price:218
            ,price:78.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkJ5TIS/oBXtQ.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkJ65xM/u4XyT.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkJrHcC/K8cQS.jpg'
                ,'http://pic.yupoo.com/yige2002/DOkJrR72/15uMdu.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUwArGM/zGWS9.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwq13X/14Zqtg.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwqebR/n4rFV.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwqmwq/TtjzU.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwBbo9/rIEK.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwBaIk/2s2pv.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwBjaO/aQ37Y.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFggBZc/dPKey.png'
                ,'http://pic.yupoo.com/yige2002/DTFggJvJ/a492Q.png'
                ,'http://pic.yupoo.com/yige2002/DTFfXGkg/mTpKY.png'
                ,null
            ]
        },

        {
            pid:608
            ,cid:4
            ,title:'成人用品 4U 淫纹G皇 女用自慰器'
            ,volume:48
            ,recentvolume:16
            ,org_price:298
            ,price:198.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOkJtBZF/r6vQ1.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOkJPhmU/100Rkz.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DRUx07cN/dACUd.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUx0p90/xYt5a.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwQGl1/tHEK5.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUwRps7/DCJL0.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUx3u3S/f1JvU.gif'
                ,'http://pic.yupoo.com/yige2002/DRUx52vT/9lPJf.jpg'
                ,'http://pic.yupoo.com/yige2002/DRUx5Qq8/SbFPK.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFggBZc/dPKey.png'
                ,'http://pic.yupoo.com/yige2002/DTFggJvJ/a492Q.png'
                ,'http://pic.yupoo.com/yige2002/DTFfXGkg/mTpKY.png'
                ,null
            ]
        },

        null
    ]