/**
 * Created by lishiming on 14-6-11.
 */
exports.productarr=
    [
        {
            pid:41
            ,cid:3
            ,title:'3D美臀实体逼真 美臀佳穴私密 阴臀倒模'
            ,volume:84
            ,recentvolume:31
            ,org_price:199
            ,price:118.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3GlZxr/9inI6.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmszsiJ/UrQ5D.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmszNsH/VDmUZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmszWzM/QUz5C.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ4t9zzg/10WX0V.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4t9Nlu/KwXRl.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4t9wzY/VRTPG.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmsA3o6/2vCXE.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmsAcPw/Kxlg4.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmsAkrV/neUN.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:42
            ,cid:3
            ,title:'AV女优青春少女小萝莉双姐妹名器倒模'
            ,volume:56
            ,recentvolume:21
            ,org_price:88
            ,price:57.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3GneDF/ovzpz.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmtokGE/BQWCx.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmtoNol/ziMf0.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmtoYzp/vvFrF.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ4wNiV2/6qNA1.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4wNhWy/2G5Fy.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4wNNgc/10RgIt.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmsKY53/12G6n6.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4wMg1E/oIwDW.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmtplda/13bimj.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmtpvYm/6Vavn.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:43
            ,cid:3
            ,title:'FunZone撸管神器 可乐蛋勃乐套自慰鸡蛋'
            ,volume:26
            ,recentvolume:14
            ,org_price:49
            ,price:34.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3Gmo0z/14VcyU.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmulTSp/uBxGQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmulDzp/9QVHm.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ4znG2D/Isg70.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4znCXI/5k3gJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmulMwQ/a5WLm.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmumfLq/sS0Xp.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmum0vV/7jxrb.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmumi2C/LaTME.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmumBqx/JmNnP.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmumMAM/Px7YZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmumBvq/mLFgY.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmumHMF/Ym2RV.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmumQqK/xjyH7.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmtJ9XK/JWVJA.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:44
            ,cid:3
            ,title:'丰乳妹大波妹男用小实体娃娃 光棍节 全年最低'
            ,volume:21
            ,recentvolume:3
            ,org_price:55
            ,price:31.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3GmSuI/gQAg3.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmvcSkb/zDb5i.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmvdwYg/ycbyY.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmuzVgA/Yayh5.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ4CaQ2J/fuQEx.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmvcU0q/kEUwZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4Bov2j/lSD2s.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmvdLeO/dk6g9.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4Cah6O/120etE.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmvebwp/9KD4Z.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:45
            ,cid:3
            ,title:'久兴幻魅真人倒模手动飞机杯'
            ,volume:45
            ,recentvolume:16
            ,org_price:88
            ,price:57.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3GnOKe/WohVT.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmxh1Pe/eDBdG.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmxgWM8/K8jO7.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmxhfX6/WYaj4.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHmxgoro/14E5Ub.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:46
            ,cid:3
            ,title:'欲火旋风二代电动飞机杯吞舌尖上的诱惑2代口交杯'
            ,volume:16
            ,recentvolume:7
            ,org_price:440
            ,price:189.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOgvCMj3/SRc5M.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOgvCUey/zWLNK.jpg'
                ,'http://pic.yupoo.com/yige2002/DOgvXFHd/fnN5X.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHmxqjkb/IFYzJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4HCHcT/11rR69.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmy4EQ8/mmyRx.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4HD14m/WkJT9.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmy4s3I/12woUP.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmy4AIi/NIv6h.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmy4NLE/PrABS.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmy5bDN/CSOte.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4HEBEU/KHz4O.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmy5oz9/MTNae.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4HCtKv/Xnxgz.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmxrCnI/nmIMo.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmy5vmC/pLWcs.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:47
            ,cid:3
            ,title:'倍儿性桃花岛真人阴臀倒模 飞一样的感觉'
            ,volume:32
            ,recentvolume:5
            ,org_price:45
            ,price:30
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3GnU2e/kYBvI.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmC6M8Q/mqHRF.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmC76RZ/5tmhe.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmBt4Ey/Kuc3k.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ4K0Yw2/2XtgL.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4K1fNK/PwmN5.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4JeNJo/FEDzm.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:48
            ,cid:3
            ,title:'名器飞机杯真人体温USB加热'
            ,volume:52
            ,recentvolume:12
            ,org_price:30
            ,price:14.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3Gn0PY/F8iuf.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmFmRll/Z6Pgv.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmFmzfT/DQTFy.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHmFmAdg/116KNS.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:49
            ,cid:3
            ,title:'日本男优终极利器 延时训练器'
            ,volume:38
            ,recentvolume:14
            ,org_price:48
            ,price:31.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/E1DDZX3f/XB1Y1.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmQcuPk/BLrqv.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQcmrp/11cc57.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmPyxCr/rFDPA.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ4OibdA/8Bbj.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4Oip81/14jThM.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4OihVS/8fGc.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQcLHq/uzfUl.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmPyJNx/ZHltN.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQcyc2/15hKS4.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQcPOO/16lSd.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQd9Lt/icvEs.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmPz7r8/MUOiN.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQdb2n/129tJ9.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQdiRR/5n50z.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQddKJ/VXUvN.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQdmI4/f5gyn.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmPzLGa/Ea0mx.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQdAHS/kgPex.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQdJpy/11CIIX.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQdY07/RKluM.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQe8sm/3XuOK.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:50
            ,cid:3
            ,title:'玩爆潮品MFONES取悦电动震动飞机杯 头牌推荐'
            ,volume:46
            ,recentvolume:17
            ,org_price:169
            ,price:86.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3GoIJl/ELk7x.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmRifmR/neiH9.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmRiHJP/I39hX.gif'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ4Rvsbw/12xa9W.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmRisVP/YewxL.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmRiHRv/i5e1E.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4ShXPA/13YLkD.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQF7df/l4JM0.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4RvN5X/V0kG0.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQFllm/8O4kQ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmRjjYx/Q5fgj.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmRjGyo/fICF9.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmRjoO6/VkbFc.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmRjFxM/Y6wsn.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4ShXER/5UAxS.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmRk2Q4/2PGu3.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmRk2vo/HbbCF.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQGtwG/DACtg.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmQElRE/dO2D6.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:51
            ,cid:3
            ,title:'男女通用强力吸附后庭拉珠'
            ,volume:98
            ,recentvolume:24
            ,org_price:69
            ,price:33.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3GnMXN/1tGBR.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmSscPy/2mov4.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmROzNL/FhzzF.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmSsDOr/8i7LJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmStmln/ATn4o.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmStsrh/EFxt3.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ4VObAI/bJKOs.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmROaaB/4T7Fc.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmSs5EM/uptAC.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmSsein/XO3pH.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4VOBRh/wV4wz.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmSsNBx/Cbbix.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmSsuCq/f0Rzi.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4VOVlv/T8bV0.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmRP0pR/SYkGk.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmSt0Q0/H0CbZ.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4VP2fg/oGR7i.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmRPl5T/LtTbK.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmStjau/Z4HTo.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4V1Vxa/In9Lw.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmStoEz/Q0bNL.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmStF9I/Wgkhi.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmSu3w1/LFUca.gif'
                ,'http://pic.yupoo.com/yige2002/DHmSrN6B/RRuhF.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:52
            ,cid:3
            ,title:'百乐前列腺按摩棒'
            ,volume:42
            ,recentvolume:12
            ,org_price:60
            ,price:48
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3GnVEH/AyeOK.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmTPLZv/OM00H.gif'
                ,'http://pic.yupoo.com/yige2002/DHmTPHo8/Wrz4B.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmTPFTf/Efx5b.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ4XS0Sx/V7rTv.gif'
                ,'http://pic.yupoo.com/yige2002/DJ4XScnr/6f6Cf.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ4XSAhn/8AbOr.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:53
            ,cid:3
            ,title:'百乐大力神4频电动超爽飞机杯'
            ,volume:78
            ,recentvolume:21
            ,org_price:159
            ,price:72
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3Go2sV/n6ys4.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmUohkX/24xo2.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmUo1RE/p8vPM.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ5oSWjn/jYm7f.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5oSIlr/DhtxM.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmUoj8c/oi5S7.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmUooEz/T3cRJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmTKBhJ/ksvRG.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmUop0Z/iHJYi.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:54
            ,cid:3
            ,title:'百乐大男人空心阳具男用加长套增长6厘米延时阴茎增大增粗'
            ,volume:66
            ,recentvolume:21
            ,org_price:39
            ,price:24
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3GoYmj/phUDI.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmVbYa0/SKHOt.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmVbSIE/yS98u.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHmVbOWt/dVCib.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5qzH15/yA9M1.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5qyTmH/UnWwa.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:55
            ,cid:3
            ,title:'真的好厉害 男性增大脉冲理疗环电机理疗器 全年最低'
            ,volume:39
            ,recentvolume:26
            ,org_price:98
            ,price:72
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3GoWqq/EwFNz.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmVIpm3/xgZ22.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmVIhyS/m2jti.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmVIMcq/NQiFU.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ5txzA6/G5HfF.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5tyr3Q/gJIPS.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5txh0x/mKHJj.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmVIrDf/fdAkb.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmVIILj/ZMTGz.gif'
                ,'http://pic.yupoo.com/yige2002/DHmVIO6X/j2xuh.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmVJ9SM/LwG5K.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:56
            ,cid:3
            ,title:'积之美爱之吻极品恋人一口咬定男用电动口交阴交自慰杯器飞机杯'
            ,volume:81
            ,recentvolume:17
            ,org_price:299
            ,price:187.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DOgG8uW5/RmvAo.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DOgG99uO/U6hl8.jpg'
                ,'http://pic.yupoo.com/yige2002/DOgG9kft/sEgoW.jpg'
                ,'http://pic.yupoo.com/yige2002/DOgG9C8v/OYh3C.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHmVQAjP/OQfKS.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5wCFQ1/UurFg.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5vQpQR/PblvR.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmWv4jz/c5NvV.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5wCVFC/6kRc6.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmWv0eh/QnRqg.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmWvbpq/8O2t3.jpg'
                ,'http://pic.yupoo.com/yige2002/DHuiqRBz/aRrqo.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmVRpKf/mIn3L.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmWvnr5/xKY83.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmWvmkU/6DZSh.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmVRHqg/CSqsR.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmWvvRT/xJ8rw.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmWvNyO/4KQri.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmWvNwT/p2Vgy.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmWvWjb/BHI2w.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmWuBFc/m2QS0.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:57
            ,cid:3
            ,title:'自慰狼友前列腺按摩棒'
            ,volume:64
            ,recentvolume:26
            ,org_price:56
            ,price:43.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3Go9IJ/CuTtL.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmXxWJe/10dhri.gif'
                ,'http://pic.yupoo.com/yige2002/DHmXxW4r/RCRc2.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmXyb8I/11XBVK.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmXyxmb/oqeHc.jpg'
                ,null
            ]
            ,detailpics:
            [
                null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:58
            ,cid:3
            ,title:'震动版太空杯 特价优惠'
            ,volume:65
            ,recentvolume:31
            ,org_price:80
            ,price:42
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3GohV6/7Gmci.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmXVkRz/VSeQo.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYzQYu/kWMI4.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ5yFL5R/vGjqk.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYzac1/N9Uxg.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYziM0/WhGt6.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYztQP/HdvB0.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5yEJh6/EvC0J.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYzxHl/vFd0y.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYzNOB/NMiMP.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYzM6K/3wCzn.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:59
            ,cid:3
            ,title:'香港邦爱电动震动处女阴交口娇肛交飞机杯 头牌推荐'
            ,volume:78
            ,recentvolume:32
            ,org_price:199
            ,price:156
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3Gpy3e/PcWfL.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHmZl9Vx/hvtLJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZlouX/bYkMG.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DHmYHdtG/JC0vt.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYHwZG/hdrrd.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5AFDHA/14GGFA.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZls4W/IW0kW.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYHPMq/11cdia.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZm6Wu/27Rz4.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZmdHv/swZXN.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYIcfV/dYVYF.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZm4AR/GyGMi.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZmfNi/Y2OZu.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZmdZ4/aUdaH.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZmnb5/EufcF.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYIGYb/otTt4.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZmuYn/8Lmlg.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZmLCh/129Bz9.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZn7Xq/ITtZE.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmZmQCM/91j6y.jpg'
                ,'http://pic.yupoo.com/yige2002/DHmYJcz8/d7F6C.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        {
            pid:60
            ,cid:3
            ,title:'香港雷霆首款可自动伸缩的飞机杯'
            ,volume:55
            ,recentvolume:21
            ,org_price:388
            ,price:238.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DH3Gq5u6/awu48.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DHn3GQeL/x1AX5.jpg'
                ,'http://pic.yupoo.com/yige2002/DHn338S2/Q0dxy.jpg'
                ,'http://pic.yupoo.com/yige2002/DHn3H9LU/MaPU5.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DJ5DvzeZ/M6Wsf.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5DwGfL/cAriI.jpg'
                ,'http://pic.yupoo.com/yige2002/DHn3GWSp/tGsBe.jpg'
                ,'http://pic.yupoo.com/yige2002/DJ5Dv9Sn/EyKw5.jpg'
                ,'http://pic.yupoo.com/yige2002/DHn3HzLE/NQHXh.jpg'
                ,'http://pic.yupoo.com/yige2002/DHn3Hf3v/CkbYC.jpg'
                ,'http://pic.yupoo.com/yige2002/DHn3HvUm/2hbpJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHn3Hrvh/xZONJ.jpg'
                ,'http://pic.yupoo.com/yige2002/DHn3HzO1/13jhjT.jpg'
                ,'http://pic.yupoo.com/yige2002/DHn3HQ7J/SO91v.jpg'
                ,'http://pic.yupoo.com/yige2002/DHn347wX/liUvY.jpg'
                ,'http://pic.yupoo.com/yige2002/DHn3HVoB/3qzKC.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFfVwjL/RrOEB.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVqvk/C6MY0.png'
                ,'http://pic.yupoo.com/yige2002/DTFfVCgS/Tts2U.png'
                ,null
            ]
        },

        null
    ]