/**
 * Created by lishiming on 14-6-11.
 */
exports.productarr=
    [
        {
            pid:221
            ,cid:1
            ,title:'制服诱惑 性感旗袍 透视超短裙 复古旗袍'
            ,volume:51
            ,recentvolume:24
            ,org_price:100.00
            ,price:25.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYdXv7ch/6A8uZ.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYdXv9m7/HcLKO.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXiHKP/1554b9.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYdXvecs/kBU5X.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXvyx6/K0hwB.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXuZAX/h8pqV.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXvQ7T/JyYu3.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXvSAo/QwmIG.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXvRLZ/fKkTV.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXw4PQ/u2MFW.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXyxU3/OPYI7.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdXubj9/JcGjg.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:222
            ,cid:1
            ,title:'蕾丝日本和服睡裙日系印花性感和服套装'
            ,volume:65
            ,recentvolume:23
            ,org_price:150
            ,price:45.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYdYfg4v/IQyYs.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYdYfYDu/SJs0M.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYgcll/zGRUZ.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYdY3GH6/AYPUx.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYh30K/yXBON.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYhovJ/bcyPW.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYgYtU/HpkSH.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYh3jx/iQYtA.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        {
            pid:223
            ,cid:1
            ,title:'刺绣旗袍中国风技师夜店服DS演出服'
            ,volume:65
            ,recentvolume:32
            ,org_price:198.00
            ,price:80.00
            ,state:1
            ,stamper:''
            ,pic_url:'http://pic.yupoo.com/yige2002/DYdYrlm8/6299.jpg'
            ,time:0
            ,gallery:
            [
                'http://pic.yupoo.com/yige2002/DYdYEMrS/dyorf.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYEqa2/hT3wi.jpg'
                ,null
            ]
            ,detailpics:
            [
                'http://pic.yupoo.com/yige2002/DYdYEAKO/IZWhp.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYFfmi/A0tkW.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYFCcc/11p7sm.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYI1QP/gKRoz.jpg'
                ,'http://pic.yupoo.com/yige2002/DYdYFbPM/77zmQ.jpg'
                ,null
            ]
            ,experience:
            [
                'http://pic.yupoo.com/yige2002/DTFg1SMJ/Sie0J.png'
                ,'http://pic.yupoo.com/yige2002/DTFfIMaD/ZW8MX.png'
                ,'http://pic.yupoo.com/yige2002/DTFg2scC/UZE1w.png'
                ,null
            ]
        },

        null
    ]